"""One-off dev tool -- NOT imported by any runtime code, NOT a DB client.

Prints the SYNCED SQL block for the granular (resource, action) permission
grants derived by rbac_template.derive_default_actions() for each of the 14
built-in roles. The output is meant to be reviewed and pasted into
backend/db/seed_rbac_template.sql's granular-grants section -- generated
once and committed as static SQL, same convention as every other file under
backend/db/, rather than re-derived at seed time.

Usage (from backend/):
    python -m app.generate_rbac_template_actions_sql

"Synced", not just appended: for every (role, resource) pair across the
FULL public.permission_actions catalog (CATALOG_ACTIONS below) -- not only
the resources a role is currently granted -- this first deletes any
existing _template grant for that role+resource that ISN'T in the role's
current derived action set (clearing it out entirely if the role's current
derived set for that resource is now empty), then inserts whatever's
missing from the current set. Re-running this after rbac_template.py's
derivation rules change keeps _template's own rows exactly in sync instead
of accumulating stale grants alongside new ones -- the same bug class as
`core_role_permissions` ending up with both `leave_approval.v` AND
`leave_approval.e` linked to one role if only additive INSERTs are used.
This ONLY ever targets _template's own sentinel-company rows, never a real
tenant (see add_provision_tenant_rbac_function.sql for how a tenant's own
customizations are protected once provisioned).
"""

from .rbac_columns import BUILTIN_ROLES, COLUMN_KEYS, DEFAULT_MATRIX
from .rbac_template import CATALOG_ACTIONS, derive_default_actions

TEMPLATE_COMPANY_ID = "11111111-1111-1111-1111-111111111111"


def _sql_quote(value: str) -> str:
    return value.replace("'", "''")


def main() -> None:
    # (resource, action) -> code, deduplicated across every role so each
    # catalog permission row is only ever inserted once. Catalog rows are
    # never deleted here -- an old code no longer used by any role is just
    # an unreferenced row, harmless to leave behind.
    all_pairs: dict[tuple[str, str], str] = {}
    per_role: list[tuple[str, dict[str, list[str]]]] = []

    for role_name in BUILTIN_ROLES:
        matrix = dict(zip(COLUMN_KEYS, DEFAULT_MATRIX[role_name].split(",")))
        granted = derive_default_actions(role_name, matrix)
        per_role.append((role_name, granted))
        for resource, actions in granted.items():
            for action in actions:
                all_pairs[(resource, action)] = f"{resource}.{action}"

    print("-- Auto-generated by: python -m app.generate_rbac_template_actions_sql")
    print("-- Do not hand-edit the VALUES lists below -- regenerate instead if the")
    print("-- derivation rules in backend/app/rbac_template.py change.")
    print()
    print("-- Granular action permissions (one row per distinct (resource, action)")
    print("-- pair used by any built-in role's current derived defaults).")
    print("INSERT INTO _template.core_permissions (id, code, module, resource, action)")
    print("SELECT gen_random_uuid(), v.code, v.resource, v.resource, v.action")
    print("FROM (VALUES")
    rows = sorted(all_pairs.items())
    for i, ((resource, action), code) in enumerate(rows):
        comma = "," if i < len(rows) - 1 else ""
        print(f"    ('{_sql_quote(code)}', '{_sql_quote(resource)}', '{_sql_quote(action)}'){comma}")
    print(") AS v(code, resource, action)")
    print("WHERE NOT EXISTS (")
    print("    SELECT 1 FROM _template.core_permissions p WHERE p.code = v.code")
    print(");")
    print()
    print("-- Granular role_permission grants, per built-in role -- SYNCED across the")
    print("-- full resource catalog (see module docstring above).")
    resources_in_catalog = sorted(CATALOG_ACTIONS.keys())
    for role_name, granted in per_role:
        print(f"-- {role_name}")
        for resource in resources_in_catalog:
            current_codes = {f"{resource}.{action}" for action in granted.get(resource, [])}

            print("DELETE FROM _template.core_role_permissions")
            print("WHERE role_id = (")
            print("    SELECT id FROM _template.core_roles")
            print(f"    WHERE company_id = '{TEMPLATE_COMPANY_ID}' AND name = '{_sql_quote(role_name)}'")
            print(")")
            print("AND permission_id IN (")
            print("    SELECT id FROM _template.core_permissions")
            print(f"    WHERE resource = '{_sql_quote(resource)}' AND length(action) > 1")
            if current_codes:
                codes_list = ", ".join(f"'{_sql_quote(c)}'" for c in sorted(current_codes))
                print(f"      AND code NOT IN ({codes_list})")
            print(");")

            for code in sorted(current_codes):
                print("INSERT INTO _template.core_role_permissions (role_id, permission_id)")
                print("SELECT r.id, p.id")
                print("FROM _template.core_roles r, _template.core_permissions p")
                print(f"WHERE r.company_id = '{TEMPLATE_COMPANY_ID}'")
                print(f"  AND r.name = '{_sql_quote(role_name)}'")
                print(f"  AND p.code = '{_sql_quote(code)}'")
                print("  AND NOT EXISTS (")
                print("      SELECT 1 FROM _template.core_role_permissions rp")
                print("      WHERE rp.role_id = r.id AND rp.permission_id = p.id")
                print("  );")
        print()


if __name__ == "__main__":
    main()
