"""Seed data for impacgo people (HCM product company)."""

import datetime

COMPANY_NAME = "impacgo people"
COMPANY_ID   = "5b2e9307-9764-441b-a70d-29b7769d75e8"
EMAIL_DOMAIN = "impacgopeople.com"

BRANCHES = [
    {"code": "IPP-HYD", "name": "Hyderabad HQ",   "country": "India", "state": "Telangana",       "city": "Hyderabad",   "tax": "36AABCI9876P1Z1", "is_head_office": True},
    {"code": "IPP-BLR", "name": "Bengaluru Office","country": "India", "state": "Karnataka",       "city": "Bengaluru",   "tax": "29AABCI9876P1Z2", "is_head_office": False},
]

BUSINESS_UNITS = [
    {"name": "Technology",        "cost_center": "CC-IPP-100"},
    {"name": "Go-to-Market",      "cost_center": "CC-IPP-200"},
    {"name": "Corporate",         "cost_center": "CC-IPP-300"},
]

DEPARTMENTS = [
    {"code": "EXC",   "name": "Executive & Strategy",  "business_unit_name": "Corporate",     "branch_code": "IPP-HYD",
     "subs": ["Founders Office", "Strategy & Planning"],                                        "annual_budget": 15_000_000},
    {"code": "ENGG",  "name": "Engineering",            "business_unit_name": "Technology",    "branch_code": "IPP-HYD",
     "subs": ["Frontend", "Backend", "Platform & Infra", "QA & Automation"],                   "annual_budget": 60_000_000},
    {"code": "PROD",  "name": "Product Management",    "business_unit_name": "Technology",    "branch_code": "IPP-HYD",
     "subs": ["Core HCM", "Payroll & Finance", "Analytics"],                                   "annual_budget": 12_000_000},
    {"code": "DES",   "name": "Design",                "business_unit_name": "Technology",    "branch_code": "IPP-HYD",
     "subs": ["UX Research", "UI Design"],                                                      "annual_budget": 8_000_000},
    {"code": "HR",    "name": "People & HR",           "business_unit_name": "Corporate",     "branch_code": "IPP-HYD",
     "subs": ["Talent Acquisition", "HR Operations", "L&D"],                                   "annual_budget": 10_000_000},
    {"code": "FIN",   "name": "Finance & Legal",       "business_unit_name": "Corporate",     "branch_code": "IPP-HYD",
     "subs": ["Accounting", "Legal & Compliance"],                                             "annual_budget": 8_000_000},
    {"code": "SALES", "name": "Sales & Growth",        "business_unit_name": "Go-to-Market",  "branch_code": "IPP-BLR",
     "subs": ["Enterprise Sales", "SMB Sales", "Partnerships"],                                "annual_budget": 25_000_000},
    {"code": "CS",    "name": "Customer Success",      "business_unit_name": "Go-to-Market",  "branch_code": "IPP-BLR",
     "subs": ["Onboarding", "Account Management", "Support Engineering"],                      "annual_budget": 15_000_000},
]

EMPLOYEES = [
    # ── Organization Owner / CEO ──────────────────────────────────────────
    {
        "employee_code": "IPP-001",
        "first_name": "Nagasai", "last_name": "Reddy",
        "work_email": "nagasai.reddy@impacgopeople.com",
        "role_name": "Organization Owner / CEO",
        "phone": "+91-9000000001", "gender": "Male",
        "date_of_birth": datetime.date(1982, 5, 14),
        "date_of_joining": datetime.date(2019, 1, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "EXC",
        "sub_department": "Founders Office",
        "designation_name": "Managing Director",
        "team": "Leadership", "work_mode": "Hybrid", "numeric_band": 1,
        "annual_ctc": 6000000,
        "reporting_manager_code": None,
        "pan": "AAANR1000A",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900001", "bank_ifsc": "HDFC0000001",
        "qualification": "B.Tech + MBA", "institute": "IIT Hyderabad / IIM Calcutta", "specialization": "Technology Management",
        "year_of_passing": 2006, "previous_employer": "Oracle India", "experience_years": 18,
        "domain": "HCM SaaS", "skills": "Product Strategy, P&L, Fundraising, HCM Domain",
        "certifications": "PMP",
        "emergency_contact_name": "Priya Reddy", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000101",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "nagasai.r@gmail.com", "personal_phone": "+91-9100000001",
        "current_address": "Villa 5, Jubilee Hills, Hyderabad 500033",
        "permanent_address": "Villa 5, Jubilee Hills, Hyderabad 500033",
        "password": "123456",
    },
    # ── C-Level Executive ─────────────────────────────────────────────────
    {
        "employee_code": "IPP-002",
        "first_name": "Vikram", "last_name": "Nair",
        "work_email": "vikram.nair@impacgopeople.com",
        "role_name": "C-Level Executive",
        "phone": "+91-9000000002", "gender": "Male",
        "date_of_birth": datetime.date(1980, 9, 22),
        "date_of_joining": datetime.date(2019, 3, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Platform & Infra",
        "designation_name": "Chief Technology Officer",
        "team": "Leadership", "work_mode": "Hybrid", "numeric_band": 1,
        "annual_ctc": 5000000,
        "reporting_manager_code": "IPP-001",
        "pan": "BBBVN2000B",
        "bank_name": "ICICI Bank", "bank_account_no": "02699900002", "bank_ifsc": "ICIC0000001",
        "qualification": "M.Tech", "institute": "IIT Bombay", "specialization": "Computer Science",
        "year_of_passing": 2003, "previous_employer": "SAP Labs India", "experience_years": 21,
        "domain": "SaaS Engineering", "skills": "Cloud Architecture, Kubernetes, Golang, Team Building",
        "certifications": "AWS Solutions Architect Professional",
        "emergency_contact_name": "Sunitha Nair", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000102",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "vikram.nair@gmail.com", "personal_phone": "+91-9100000002",
        "current_address": "Flat 1201, Kondapur, Hyderabad 500084",
        "permanent_address": "TC 5-678, Trivandrum 695003",
        "password": "123456",
    },
    {
        "employee_code": "IPP-003",
        "first_name": "Harini", "last_name": "Krishnaswamy",
        "work_email": "harini.krishnaswamy@impacgopeople.com",
        "role_name": "C-Level Executive",
        "phone": "+91-9000000003", "gender": "Female",
        "date_of_birth": datetime.date(1983, 2, 8),
        "date_of_joining": datetime.date(2020, 6, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "FIN",
        "sub_department": "Accounting",
        "designation_name": "Chief Financial Officer",
        "team": "Leadership", "work_mode": "On-site", "numeric_band": 1,
        "annual_ctc": 4800000,
        "reporting_manager_code": "IPP-001",
        "pan": "CCCHK3000C",
        "bank_name": "Axis Bank", "bank_account_no": "91599900003", "bank_ifsc": "UTIB0000001",
        "qualification": "CA", "institute": "ICAI", "specialization": "Finance",
        "year_of_passing": 2005, "previous_employer": "Deloitte India", "experience_years": 19,
        "domain": "SaaS Finance", "skills": "Financial Planning, SaaS Metrics, M&A, SEBI Compliance",
        "certifications": "CA, CFA Level 2",
        "emergency_contact_name": "Rajesh Krishnaswamy", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000103",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "harini.k@gmail.com", "personal_phone": "+91-9100000003",
        "current_address": "Flat 802, Banjara Hills, Hyderabad 500034",
        "permanent_address": "14-5, Mylapore, Chennai 600004",
        "password": "123456",
    },
    # ── VP / Director ─────────────────────────────────────────────────────
    {
        "employee_code": "IPP-004",
        "first_name": "Aditya", "last_name": "Srinivasan",
        "work_email": "aditya.srinivasan@impacgopeople.com",
        "role_name": "VP / Director",
        "phone": "+91-9000000004", "gender": "Male",
        "date_of_birth": datetime.date(1985, 11, 30),
        "date_of_joining": datetime.date(2020, 8, 10),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Backend",
        "designation_name": "Vice President",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 2,
        "annual_ctc": 3500000,
        "reporting_manager_code": "IPP-002",
        "pan": "DDDAS4000D",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900004", "bank_ifsc": "HDFC0000002",
        "qualification": "M.Tech", "institute": "IIT Madras", "specialization": "Software Systems",
        "year_of_passing": 2008, "previous_employer": "Freshworks", "experience_years": 16,
        "domain": "Backend Engineering", "skills": "Java, Spring Boot, Microservices, PostgreSQL, Redis",
        "certifications": "GCP Professional Cloud Architect",
        "emergency_contact_name": "Deepa Srinivasan", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000104",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "aditya.s@gmail.com", "personal_phone": "+91-9100000004",
        "current_address": "Flat 1504, Gachibowli, Hyderabad 500032",
        "permanent_address": "23-4, Adyar, Chennai 600020",
        "password": "123456",
    },
    {
        "employee_code": "IPP-005",
        "first_name": "Pallavi", "last_name": "Mehta",
        "work_email": "pallavi.mehta@impacgopeople.com",
        "role_name": "VP / Director",
        "phone": "+91-9000000005", "gender": "Female",
        "date_of_birth": datetime.date(1984, 7, 15),
        "date_of_joining": datetime.date(2021, 1, 4),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "SALES",
        "sub_department": "Enterprise Sales",
        "designation_name": "Vice President",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 2,
        "annual_ctc": 3800000,
        "reporting_manager_code": "IPP-001",
        "pan": "EEEPM5000E",
        "bank_name": "Kotak Bank", "bank_account_no": "63099900005", "bank_ifsc": "KKBK0000001",
        "qualification": "MBA", "institute": "IIM Ahmedabad", "specialization": "Marketing",
        "year_of_passing": 2007, "previous_employer": "Zoho Corporation", "experience_years": 17,
        "domain": "Enterprise SaaS Sales", "skills": "Enterprise Sales, SaaS GTM, Account Management, CRM",
        "certifications": "Salesforce Sales Cloud Consultant",
        "emergency_contact_name": "Rohan Mehta", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000105",
        "blood_group": "A-", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "pallavi.mehta@gmail.com", "personal_phone": "+91-9100000005",
        "current_address": "Flat 401, Indiranagar, Bengaluru 560038",
        "permanent_address": "12-3, Borivali, Mumbai 400092",
        "password": "123456",
    },
    # ── General Manager / Sr. Manager ─────────────────────────────────────
    {
        "employee_code": "IPP-006",
        "first_name": "Suresh", "last_name": "Anand",
        "work_email": "suresh.anand@impacgopeople.com",
        "role_name": "General Manager / Sr. Manager",
        "phone": "+91-9000000006", "gender": "Male",
        "date_of_birth": datetime.date(1986, 3, 18),
        "date_of_joining": datetime.date(2020, 11, 2),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Backend",
        "designation_name": "Senior Manager",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 3,
        "annual_ctc": 2800000,
        "reporting_manager_code": "IPP-004",
        "pan": "FFFSA6000F",
        "bank_name": "SBI", "bank_account_no": "30099900006", "bank_ifsc": "SBIN0000001",
        "qualification": "B.Tech", "institute": "BITS Pilani", "specialization": "Computer Science",
        "year_of_passing": 2008, "previous_employer": "Microsoft India", "experience_years": 16,
        "domain": "Backend / Platform Engineering", "skills": "Node.js, Python, Kafka, AWS, System Design",
        "certifications": "AWS DevOps Engineer Professional",
        "emergency_contact_name": "Meera Anand", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000106",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "suresh.anand@gmail.com", "personal_phone": "+91-9100000006",
        "current_address": "Flat 701, Hitech City, Hyderabad 500081",
        "permanent_address": "Plot 5, Pilani, Rajasthan 333031",
        "password": "123456",
    },
    {
        "employee_code": "IPP-007",
        "first_name": "Deepika", "last_name": "Rao",
        "work_email": "deepika.rao@impacgopeople.com",
        "role_name": "General Manager / Sr. Manager",
        "phone": "+91-9000000007", "gender": "Female",
        "date_of_birth": datetime.date(1987, 6, 25),
        "date_of_joining": datetime.date(2021, 4, 12),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "HR",
        "sub_department": "HR Operations",
        "designation_name": "Senior Manager",
        "team": "People & HR", "work_mode": "On-site", "numeric_band": 3,
        "annual_ctc": 2200000,
        "reporting_manager_code": "IPP-001",
        "pan": "GGGDR7000G",
        "bank_name": "ICICI Bank", "bank_account_no": "02699900007", "bank_ifsc": "ICIC0000002",
        "qualification": "MBA HR", "institute": "XLRI Jamshedpur", "specialization": "Human Resources",
        "year_of_passing": 2010, "previous_employer": "Infosys BPM", "experience_years": 14,
        "domain": "Tech HR", "skills": "HRBP, Talent Acquisition, Culture Building, OKRs, Compensation",
        "certifications": "SHRM-SCP",
        "emergency_contact_name": "Suresh Rao", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000107",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "deepika.rao@gmail.com", "personal_phone": "+91-9100000007",
        "current_address": "Flat 302, Madhapur, Hyderabad 500081",
        "permanent_address": "12-5, Mangalore 575001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-008",
        "first_name": "Rajeev", "last_name": "Pillai",
        "work_email": "rajeev.pillai@impacgopeople.com",
        "role_name": "General Manager / Sr. Manager",
        "phone": "+91-9000000008", "gender": "Male",
        "date_of_birth": datetime.date(1985, 12, 10),
        "date_of_joining": datetime.date(2021, 7, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "CS",
        "sub_department": "Account Management",
        "designation_name": "Senior Manager",
        "team": "Customer Success", "work_mode": "Hybrid", "numeric_band": 3,
        "annual_ctc": 2400000,
        "reporting_manager_code": "IPP-005",
        "pan": "HHHXP8000H",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900008", "bank_ifsc": "HDFC0000003",
        "qualification": "MBA", "institute": "IIM Kozhikode", "specialization": "Strategy",
        "year_of_passing": 2009, "previous_employer": "Darwinbox", "experience_years": 15,
        "domain": "SaaS Customer Success", "skills": "Customer Success, SaaS Renewals, Churn Reduction, NPS",
        "certifications": "Gainsight CS Certification",
        "emergency_contact_name": "Asha Pillai", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000108",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "rajeev.pillai@gmail.com", "personal_phone": "+91-9100000008",
        "current_address": "Flat 504, Koramangala, Bengaluru 560034",
        "permanent_address": "TC 2-45, Kochi 682001",
        "password": "123456",
    },
    # ── Manager ───────────────────────────────────────────────────────────
    {
        "employee_code": "IPP-009",
        "first_name": "Karthik", "last_name": "Venkataraman",
        "work_email": "karthik.venkataraman@impacgopeople.com",
        "role_name": "Manager",
        "phone": "+91-9000000009", "gender": "Male",
        "date_of_birth": datetime.date(1989, 4, 5),
        "date_of_joining": datetime.date(2021, 9, 6),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Frontend",
        "designation_name": "Manager",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 4,
        "annual_ctc": 2000000,
        "reporting_manager_code": "IPP-006",
        "pan": "IIIKV9000I",
        "bank_name": "Axis Bank", "bank_account_no": "91599900009", "bank_ifsc": "UTIB0000002",
        "qualification": "B.Tech", "institute": "NIT Trichy", "specialization": "Computer Science",
        "year_of_passing": 2011, "previous_employer": "Chargebee", "experience_years": 13,
        "domain": "Frontend Engineering", "skills": "Flutter, React, TypeScript, GraphQL, Performance",
        "certifications": "Flutter Certified Application Developer",
        "emergency_contact_name": "Swetha Venkataraman", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000109",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "karthik.v@gmail.com", "personal_phone": "+91-9100000009",
        "current_address": "Flat 1102, Kondapur, Hyderabad 500084",
        "permanent_address": "5-6, Trichy 620001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-010",
        "first_name": "Ananya", "last_name": "Chakraborty",
        "work_email": "ananya.chakraborty@impacgopeople.com",
        "role_name": "Manager",
        "phone": "+91-9000000010", "gender": "Female",
        "date_of_birth": datetime.date(1990, 8, 18),
        "date_of_joining": datetime.date(2022, 1, 17),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "PROD",
        "sub_department": "Core HCM",
        "designation_name": "Manager",
        "team": "Product", "work_mode": "Hybrid", "numeric_band": 4,
        "annual_ctc": 2200000,
        "reporting_manager_code": "IPP-002",
        "pan": "JJJAC0000J",
        "bank_name": "SBI", "bank_account_no": "30099900010", "bank_ifsc": "SBIN0000002",
        "qualification": "B.Tech + MBA", "institute": "IIT Kharagpur / ISB Hyderabad", "specialization": "Product Management",
        "year_of_passing": 2013, "previous_employer": "Keka HR", "experience_years": 11,
        "domain": "HCM Product", "skills": "Product Roadmap, User Research, PRD, Agile, HCM Domain",
        "certifications": "Certified Product Manager (CPM)",
        "emergency_contact_name": "Rahul Chakraborty", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000110",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "ananya.c@gmail.com", "personal_phone": "+91-9100000010",
        "current_address": "Flat 603, Madhapur, Hyderabad 500081",
        "permanent_address": "34-5, Kolkata 700019",
        "password": "123456",
    },
    {
        "employee_code": "IPP-011",
        "first_name": "Sanjay", "last_name": "Gupta",
        "work_email": "sanjay.gupta@impacgopeople.com",
        "role_name": "Manager",
        "phone": "+91-9000000011", "gender": "Male",
        "date_of_birth": datetime.date(1988, 1, 28),
        "date_of_joining": datetime.date(2021, 11, 15),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "SALES",
        "sub_department": "SMB Sales",
        "designation_name": "Manager",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 4,
        "annual_ctc": 2100000,
        "reporting_manager_code": "IPP-005",
        "pan": "KKKXG1000K",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900011", "bank_ifsc": "HDFC0000004",
        "qualification": "MBA", "institute": "Symbiosis Pune", "specialization": "Sales & Marketing",
        "year_of_passing": 2011, "previous_employer": "Razorpay", "experience_years": 13,
        "domain": "SaaS SMB Sales", "skills": "SaaS Sales, SMB Closing, Salesforce, Demo, Negotiation",
        "certifications": "Salesforce Administrator",
        "emergency_contact_name": "Priya Gupta", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000111",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "sanjay.gupta@gmail.com", "personal_phone": "+91-9100000011",
        "current_address": "Flat 202, HSR Layout, Bengaluru 560102",
        "permanent_address": "H.No 5-23, Kanpur 208001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-012",
        "first_name": "Nithya", "last_name": "Subramaniam",
        "work_email": "nithya.subramaniam@impacgopeople.com",
        "role_name": "Manager",
        "phone": "+91-9000000012", "gender": "Female",
        "date_of_birth": datetime.date(1991, 10, 3),
        "date_of_joining": datetime.date(2022, 3, 7),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "CS",
        "sub_department": "Onboarding",
        "designation_name": "Manager",
        "team": "Customer Success", "work_mode": "Hybrid", "numeric_band": 4,
        "annual_ctc": 1900000,
        "reporting_manager_code": "IPP-008",
        "pan": "LLLNS2000L",
        "bank_name": "ICICI Bank", "bank_account_no": "02699900012", "bank_ifsc": "ICIC0000003",
        "qualification": "MBA", "institute": "TAPMI Manipal", "specialization": "Marketing",
        "year_of_passing": 2014, "previous_employer": "Darwinbox", "experience_years": 10,
        "domain": "Customer Onboarding", "skills": "HCM Implementation, HRMS Configuration, Training, CS Tools",
        "certifications": "Darwinbox Certified Consultant",
        "emergency_contact_name": "Akash Subramaniam", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000112",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "nithya.s@gmail.com", "personal_phone": "+91-9100000012",
        "current_address": "Flat 304, BTM Layout, Bengaluru 560076",
        "permanent_address": "8-4, Madurai 625001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-013",
        "first_name": "Vignesh", "last_name": "Kumar",
        "work_email": "vignesh.kumar@impacgopeople.com",
        "role_name": "Manager",
        "phone": "+91-9000000013", "gender": "Male",
        "date_of_birth": datetime.date(1990, 5, 20),
        "date_of_joining": datetime.date(2022, 6, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "QA & Automation",
        "designation_name": "Manager",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 4,
        "annual_ctc": 1800000,
        "reporting_manager_code": "IPP-006",
        "pan": "MMMVK3000M",
        "bank_name": "Axis Bank", "bank_account_no": "91599900013", "bank_ifsc": "UTIB0000003",
        "qualification": "B.Tech", "institute": "Anna University", "specialization": "Information Technology",
        "year_of_passing": 2012, "previous_employer": "ThoughtWorks", "experience_years": 12,
        "domain": "Quality Engineering", "skills": "Selenium, Playwright, API Testing, CI/CD, Test Planning",
        "certifications": "ISTQB Advanced",
        "emergency_contact_name": "Kavitha Kumar", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000113",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "vignesh.kumar@gmail.com", "personal_phone": "+91-9100000013",
        "current_address": "Flat 502, Madhapur, Hyderabad 500081",
        "permanent_address": "12-5, Coimbatore 641001",
        "password": "123456",
    },
    # ── Team Lead ─────────────────────────────────────────────────────────
    {
        "employee_code": "IPP-014",
        "first_name": "Akshay", "last_name": "Desai",
        "work_email": "akshay.desai@impacgopeople.com",
        "role_name": "Team Lead",
        "phone": "+91-9000000014", "gender": "Male",
        "date_of_birth": datetime.date(1992, 3, 14),
        "date_of_joining": datetime.date(2022, 2, 14),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Frontend",
        "designation_name": "Senior Engineer",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1600000,
        "reporting_manager_code": "IPP-009",
        "pan": "NNNXD4000N",
        "bank_name": "SBI", "bank_account_no": "30099900014", "bank_ifsc": "SBIN0000003",
        "qualification": "B.Tech", "institute": "VNIT Nagpur", "specialization": "Computer Science",
        "year_of_passing": 2014, "previous_employer": "Mindtree", "experience_years": 10,
        "domain": "Flutter / React Frontend", "skills": "Flutter, Dart, React, TypeScript, GraphQL, Figma",
        "certifications": "Flutter Certified Developer",
        "emergency_contact_name": "Snehal Desai", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000114",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "akshay.desai@gmail.com", "personal_phone": "+91-9100000014",
        "current_address": "Flat 303, Gachibowli, Hyderabad 500032",
        "permanent_address": "34-2, Nagpur 440010",
        "password": "123456",
    },
    {
        "employee_code": "IPP-015",
        "first_name": "Poornima", "last_name": "Iyer",
        "work_email": "poornima.iyer@impacgopeople.com",
        "role_name": "Team Lead",
        "phone": "+91-9000000015", "gender": "Female",
        "date_of_birth": datetime.date(1993, 7, 9),
        "date_of_joining": datetime.date(2022, 5, 2),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Backend",
        "designation_name": "Senior Engineer",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1700000,
        "reporting_manager_code": "IPP-006",
        "pan": "OOOXI5000O",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900015", "bank_ifsc": "HDFC0000005",
        "qualification": "B.Tech", "institute": "NIT Calicut", "specialization": "Computer Science",
        "year_of_passing": 2015, "previous_employer": "Sify Technologies", "experience_years": 9,
        "domain": "Backend / API Engineering", "skills": "Python FastAPI, PostgreSQL, Redis, Docker, AWS Lambda",
        "certifications": "AWS Developer Associate",
        "emergency_contact_name": "Krishnan Iyer", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000115",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "poornima.iyer@gmail.com", "personal_phone": "+91-9100000015",
        "current_address": "Flat 204, Madhapur, Hyderabad 500081",
        "permanent_address": "TC 3-45, Calicut 673001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-016",
        "first_name": "Rahul", "last_name": "Bose",
        "work_email": "rahul.bose@impacgopeople.com",
        "role_name": "Team Lead",
        "phone": "+91-9000000016", "gender": "Male",
        "date_of_birth": datetime.date(1992, 11, 17),
        "date_of_joining": datetime.date(2022, 8, 8),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "CS",
        "sub_department": "Support Engineering",
        "designation_name": "Senior Executive",
        "team": "Customer Success", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1500000,
        "reporting_manager_code": "IPP-008",
        "pan": "PPPRB6000P",
        "bank_name": "Canara Bank", "bank_account_no": "12399900016", "bank_ifsc": "CNRB0000001",
        "qualification": "B.Tech", "institute": "Jadavpur University", "specialization": "Computer Science",
        "year_of_passing": 2014, "previous_employer": "Freshdesk", "experience_years": 10,
        "domain": "Technical Support", "skills": "HCM Troubleshooting, REST APIs, SQL, JIRA, Zendesk",
        "certifications": "ITIL v4",
        "emergency_contact_name": "Maya Bose", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-9000000116",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "rahul.bose@gmail.com", "personal_phone": "+91-9100000016",
        "current_address": "Flat 102, Whitefield, Bengaluru 560066",
        "permanent_address": "23-4, Kolkata 700027",
        "password": "123456",
    },
    {
        "employee_code": "IPP-017",
        "first_name": "Swati", "last_name": "Joshi",
        "work_email": "swati.joshi@impacgopeople.com",
        "role_name": "Team Lead",
        "phone": "+91-9000000017", "gender": "Female",
        "date_of_birth": datetime.date(1993, 4, 22),
        "date_of_joining": datetime.date(2022, 10, 3),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "QA & Automation",
        "designation_name": "Senior Engineer",
        "team": "Engineering", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 1550000,
        "reporting_manager_code": "IPP-013",
        "pan": "QQQSJ7000Q",
        "bank_name": "SBI", "bank_account_no": "30099900017", "bank_ifsc": "SBIN0000004",
        "qualification": "B.E.", "institute": "COEP Pune", "specialization": "Computer Engineering",
        "year_of_passing": 2015, "previous_employer": "Persistent Systems", "experience_years": 9,
        "domain": "QA Automation", "skills": "Playwright, Selenium, Appium, TestNG, BDD",
        "certifications": "ISTQB Certified",
        "emergency_contact_name": "Pradeep Joshi", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000117",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "swati.joshi@gmail.com", "personal_phone": "+91-9100000017",
        "current_address": "Flat 201, Kondapur, Hyderabad 500084",
        "permanent_address": "14-3, Pune 411005",
        "password": "123456",
    },
    # ── HR / Recruitment Staff ────────────────────────────────────────────
    {
        "employee_code": "IPP-018",
        "first_name": "Manasa", "last_name": "Reddy",
        "work_email": "manasa.reddy@impacgopeople.com",
        "role_name": "HR / Recruitment Staff",
        "phone": "+91-9000000018", "gender": "Female",
        "date_of_birth": datetime.date(1994, 9, 11),
        "date_of_joining": datetime.date(2022, 4, 4),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "HR",
        "sub_department": "Talent Acquisition",
        "designation_name": "Senior Executive",
        "team": "People & HR", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 900000,
        "reporting_manager_code": "IPP-007",
        "pan": "RRRXR8000R",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900018", "bank_ifsc": "HDFC0000006",
        "qualification": "MBA HR", "institute": "Hyderabad University", "specialization": "Human Resources",
        "year_of_passing": 2017, "previous_employer": "GreyOrange", "experience_years": 7,
        "domain": "Tech Recruiting", "skills": "Tech Recruitment, ATS, LinkedIn Sourcing, Naukri, HRMS",
        "certifications": "",
        "emergency_contact_name": "Ramaiah Reddy", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000118",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "manasa.reddy@gmail.com", "personal_phone": "+91-9100000018",
        "current_address": "Flat 401, Kukatpally, Hyderabad 500072",
        "permanent_address": "H.No 5-6, Nellore 524001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-019",
        "first_name": "Tejaswi", "last_name": "Patel",
        "work_email": "tejaswi.patel@impacgopeople.com",
        "role_name": "HR / Recruitment Staff",
        "phone": "+91-9000000019", "gender": "Female",
        "date_of_birth": datetime.date(1996, 2, 5),
        "date_of_joining": datetime.date(2023, 1, 16),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "HR",
        "sub_department": "HR Operations",
        "designation_name": "Executive",
        "team": "People & HR", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 650000,
        "reporting_manager_code": "IPP-007",
        "pan": "SSSXP9000S",
        "bank_name": "ICICI Bank", "bank_account_no": "02699900019", "bank_ifsc": "ICIC0000004",
        "qualification": "MBA HR", "institute": "Osmania University", "specialization": "HR",
        "year_of_passing": 2019, "previous_employer": None, "experience_years": 3,
        "domain": "HR Generalist", "skills": "Onboarding, Payroll Coordination, HRIS, Employee Engagement",
        "certifications": "",
        "emergency_contact_name": "Suresh Patel", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000119",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "tejaswi.patel@gmail.com", "personal_phone": "+91-9100000019",
        "current_address": "Flat 102, Ameerpet, Hyderabad 500016",
        "permanent_address": "H.No 4-7, Surat 395001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-020",
        "first_name": "Arun", "last_name": "Krishnan",
        "work_email": "arun.krishnan@impacgopeople.com",
        "role_name": "HR / Recruitment Staff",
        "phone": "+91-9000000020", "gender": "Male",
        "date_of_birth": datetime.date(1995, 6, 29),
        "date_of_joining": datetime.date(2022, 9, 5),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "HR",
        "sub_department": "Talent Acquisition",
        "designation_name": "Senior Executive",
        "team": "People & HR", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 850000,
        "reporting_manager_code": "IPP-007",
        "pan": "TTTXK0000T",
        "bank_name": "Axis Bank", "bank_account_no": "91599900020", "bank_ifsc": "UTIB0000004",
        "qualification": "BBA HR", "institute": "Christ University Bengaluru", "specialization": "HR",
        "year_of_passing": 2017, "previous_employer": "Unacademy", "experience_years": 6,
        "domain": "Campus + Lateral Hiring", "skills": "Campus Recruitment, Volume Hiring, LinkedIn Recruiter, ATS",
        "certifications": "",
        "emergency_contact_name": "Lakshmi Krishnan", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-9000000120",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "arun.krishnan@gmail.com", "personal_phone": "+91-9100000020",
        "current_address": "PG, Marathahalli, Bengaluru 560037",
        "permanent_address": "TC 8-9, Trivandrum 695003",
        "password": "123456",
    },
    # ── Finance / Payroll Staff ───────────────────────────────────────────
    {
        "employee_code": "IPP-021",
        "first_name": "Divyesh", "last_name": "Shah",
        "work_email": "divyesh.shah@impacgopeople.com",
        "role_name": "Finance / Payroll Staff",
        "phone": "+91-9000000021", "gender": "Male",
        "date_of_birth": datetime.date(1990, 12, 14),
        "date_of_joining": datetime.date(2022, 2, 7),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "FIN",
        "sub_department": "Accounting",
        "designation_name": "Senior Executive",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 900000,
        "reporting_manager_code": "IPP-003",
        "pan": "UUUDS1000U",
        "bank_name": "SBI", "bank_account_no": "30099900021", "bank_ifsc": "SBIN0000005",
        "qualification": "CA Inter", "institute": "ICAI", "specialization": "Accounting",
        "year_of_passing": 2013, "previous_employer": "KPMG India", "experience_years": 11,
        "domain": "SaaS Finance & Payroll", "skills": "Tally, GST, TDS, Payroll Processing, Financial Reporting",
        "certifications": "CA Inter",
        "emergency_contact_name": "Hetal Shah", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000121",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "divyesh.shah@gmail.com", "personal_phone": "+91-9100000021",
        "current_address": "Flat 201, Banjara Hills, Hyderabad 500034",
        "permanent_address": "12-3, Ahmedabad 380009",
        "password": "123456",
    },
    {
        "employee_code": "IPP-022",
        "first_name": "Lavanya", "last_name": "Deshpande",
        "work_email": "lavanya.deshpande@impacgopeople.com",
        "role_name": "Finance / Payroll Staff",
        "phone": "+91-9000000022", "gender": "Female",
        "date_of_birth": datetime.date(1993, 3, 7),
        "date_of_joining": datetime.date(2023, 3, 13),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "FIN",
        "sub_department": "Accounting",
        "designation_name": "Executive",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 650000,
        "reporting_manager_code": "IPP-003",
        "pan": "VVVXD2000V",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900022", "bank_ifsc": "HDFC0000007",
        "qualification": "B.Com", "institute": "Pune University", "specialization": "Accounting",
        "year_of_passing": 2015, "previous_employer": "Grant Thornton", "experience_years": 8,
        "domain": "Payroll & Compliance", "skills": "Payroll, PF, ESI, Professional Tax, Tally",
        "certifications": "",
        "emergency_contact_name": "Mohan Deshpande", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000122",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "lavanya.d@gmail.com", "personal_phone": "+91-9100000022",
        "current_address": "Flat 103, Madhapur, Hyderabad 500081",
        "permanent_address": "23-4, Pune 411004",
        "password": "123456",
    },
    # ── IT / System Admin ─────────────────────────────────────────────────
    {
        "employee_code": "IPP-023",
        "first_name": "Nikhil", "last_name": "Varma",
        "work_email": "nikhil.varma@impacgopeople.com",
        "role_name": "IT / System Admin",
        "phone": "+91-9000000023", "gender": "Male",
        "date_of_birth": datetime.date(1991, 8, 25),
        "date_of_joining": datetime.date(2022, 7, 11),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Platform & Infra",
        "designation_name": "Senior Executive",
        "team": "Engineering", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 1100000,
        "reporting_manager_code": "IPP-002",
        "pan": "WWWNV3000W",
        "bank_name": "Axis Bank", "bank_account_no": "91599900023", "bank_ifsc": "UTIB0000005",
        "qualification": "B.Tech", "institute": "JNTU Hyderabad", "specialization": "Computer Science",
        "year_of_passing": 2013, "previous_employer": "Wipro Technologies", "experience_years": 11,
        "domain": "DevOps & Infra", "skills": "AWS, Terraform, Kubernetes, Docker, CI/CD, Linux Admin",
        "certifications": "AWS SysOps Administrator",
        "emergency_contact_name": "Radha Varma", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-9000000123",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "nikhil.varma@gmail.com", "personal_phone": "+91-9100000023",
        "current_address": "Flat 501, Gachibowli, Hyderabad 500032",
        "permanent_address": "H.No 3-4, Vizag 530013",
        "password": "123456",
    },
    {
        "employee_code": "IPP-024",
        "first_name": "Smitha", "last_name": "Nambiar",
        "work_email": "smitha.nambiar@impacgopeople.com",
        "role_name": "IT / System Admin",
        "phone": "+91-9000000024", "gender": "Female",
        "date_of_birth": datetime.date(1994, 5, 2),
        "date_of_joining": datetime.date(2023, 2, 20),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "ENGG",
        "sub_department": "Platform & Infra",
        "designation_name": "Executive",
        "team": "Engineering", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 850000,
        "reporting_manager_code": "IPP-023",
        "pan": "XXXSN4000X",
        "bank_name": "SBI", "bank_account_no": "30099900024", "bank_ifsc": "SBIN0000006",
        "qualification": "B.Sc Computer Science", "institute": "MG University Kerala", "specialization": "Computer Science",
        "year_of_passing": 2016, "previous_employer": "HCL Infosystems", "experience_years": 7,
        "domain": "IT Operations", "skills": "Azure, Active Directory, Network Admin, ITSM, Endpoint Security",
        "certifications": "Microsoft AZ-104",
        "emergency_contact_name": "Krishnan Nambiar", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000124",
        "blood_group": "A-", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "smitha.nambiar@gmail.com", "personal_phone": "+91-9100000024",
        "current_address": "PG, HSR Layout, Bengaluru 560102",
        "permanent_address": "TC 2-34, Kochi 682002",
        "password": "123456",
    },
    # ── Professional / IC Employee (Engineers, Designers, CS, Sales) ──────
    {
        "employee_code": "IPP-025",
        "first_name": "Varun", "last_name": "Tiwari",
        "work_email": "varun.tiwari@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000025", "gender": "Male",
        "date_of_birth": datetime.date(1995, 1, 17),
        "date_of_joining": datetime.date(2022, 6, 20),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Frontend",
        "designation_name": "Software Engineer",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1400000,
        "reporting_manager_code": "IPP-014",
        "pan": "YYYXT5000Y",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900025", "bank_ifsc": "HDFC0000008",
        "qualification": "B.Tech", "institute": "NIT Warangal", "specialization": "Computer Science",
        "year_of_passing": 2017, "previous_employer": "Capgemini", "experience_years": 7,
        "domain": "Flutter Development", "skills": "Flutter, Dart, Firebase, REST APIs, Git",
        "certifications": "",
        "emergency_contact_name": "Ramesh Tiwari", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000125",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "varun.tiwari@gmail.com", "personal_phone": "+91-9100000025",
        "current_address": "PG, Madhapur, Hyderabad 500081",
        "permanent_address": "H.No 5-6, Lucknow 226010",
        "password": "123456",
    },
    {
        "employee_code": "IPP-026",
        "first_name": "Priya", "last_name": "Senthil",
        "work_email": "priya.senthil@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000026", "gender": "Female",
        "date_of_birth": datetime.date(1996, 4, 12),
        "date_of_joining": datetime.date(2023, 1, 9),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Backend",
        "designation_name": "Software Engineer",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1300000,
        "reporting_manager_code": "IPP-015",
        "pan": "ZZZXS6000Z",
        "bank_name": "ICICI Bank", "bank_account_no": "02699900026", "bank_ifsc": "ICIC0000005",
        "qualification": "B.Tech", "institute": "PSG Tech Coimbatore", "specialization": "IT",
        "year_of_passing": 2018, "previous_employer": "Zoho Corporation", "experience_years": 5,
        "domain": "Python Backend", "skills": "Python, FastAPI, SQLAlchemy, PostgreSQL, Redis",
        "certifications": "",
        "emergency_contact_name": "Senthil Kumar", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000126",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "priya.senthil@gmail.com", "personal_phone": "+91-9100000026",
        "current_address": "PG, Kondapur, Hyderabad 500084",
        "permanent_address": "8-4, Coimbatore 641018",
        "password": "123456",
    },
    {
        "employee_code": "IPP-027",
        "first_name": "Madhuri", "last_name": "Shetty",
        "work_email": "madhuri.shetty@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000027", "gender": "Female",
        "date_of_birth": datetime.date(1994, 10, 8),
        "date_of_joining": datetime.date(2022, 9, 12),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "DES",
        "sub_department": "UI Design",
        "designation_name": "Senior Designer",
        "team": "Design", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1400000,
        "reporting_manager_code": "IPP-010",
        "pan": "AAAXS7000A",
        "bank_name": "Axis Bank", "bank_account_no": "91599900027", "bank_ifsc": "UTIB0000006",
        "qualification": "B.Des", "institute": "NID Ahmedabad", "specialization": "Product Design",
        "year_of_passing": 2016, "previous_employer": "Oyo Rooms", "experience_years": 8,
        "domain": "Product / UX Design", "skills": "Figma, Prototyping, User Research, Design Systems, Accessibility",
        "certifications": "Google UX Design Certificate",
        "emergency_contact_name": "Ganesh Shetty", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000127",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "madhuri.shetty@gmail.com", "personal_phone": "+91-9100000027",
        "current_address": "Flat 302, Hitech City, Hyderabad 500081",
        "permanent_address": "12-4, Mangalore 575003",
        "password": "123456",
    },
    {
        "employee_code": "IPP-028",
        "first_name": "Shashank", "last_name": "Kulkarni",
        "work_email": "shashank.kulkarni@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000028", "gender": "Male",
        "date_of_birth": datetime.date(1993, 7, 26),
        "date_of_joining": datetime.date(2022, 11, 7),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Platform & Infra",
        "designation_name": "Senior Engineer",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1600000,
        "reporting_manager_code": "IPP-023",
        "pan": "BBBSK8000B",
        "bank_name": "SBI", "bank_account_no": "30099900028", "bank_ifsc": "SBIN0000007",
        "qualification": "B.Tech", "institute": "VIT Vellore", "specialization": "Computer Science",
        "year_of_passing": 2015, "previous_employer": "Infosys", "experience_years": 9,
        "domain": "DevOps & SRE", "skills": "Kubernetes, Prometheus, Grafana, AWS EKS, Terraform, GitHub Actions",
        "certifications": "CKA (Certified Kubernetes Administrator)",
        "emergency_contact_name": "Savita Kulkarni", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-9000000128",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "shashank.k@gmail.com", "personal_phone": "+91-9100000028",
        "current_address": "Flat 203, Madhapur, Hyderabad 500081",
        "permanent_address": "34-5, Pune 411001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-029",
        "first_name": "Charitha", "last_name": "Pillai",
        "work_email": "charitha.pillai@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000029", "gender": "Female",
        "date_of_birth": datetime.date(1995, 3, 15),
        "date_of_joining": datetime.date(2023, 4, 17),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "CS",
        "sub_department": "Account Management",
        "designation_name": "Executive",
        "team": "Customer Success", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1100000,
        "reporting_manager_code": "IPP-008",
        "pan": "CCCCP9000C",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900029", "bank_ifsc": "HDFC0000009",
        "qualification": "MBA", "institute": "IFIM Bengaluru", "specialization": "Marketing",
        "year_of_passing": 2018, "previous_employer": "Leadsquared", "experience_years": 5,
        "domain": "SaaS CS", "skills": "Account Management, Upsell, NPS, Churn, Product Demos",
        "certifications": "",
        "emergency_contact_name": "Suresh Pillai", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000129",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "charitha.pillai@gmail.com", "personal_phone": "+91-9100000029",
        "current_address": "PG, Koramangala, Bengaluru 560034",
        "permanent_address": "TC 4-56, Kochi 682016",
        "password": "123456",
    },
    {
        "employee_code": "IPP-030",
        "first_name": "Hemanth", "last_name": "Sharma",
        "work_email": "hemanth.sharma@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000030", "gender": "Male",
        "date_of_birth": datetime.date(1994, 12, 22),
        "date_of_joining": datetime.date(2022, 8, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "SALES",
        "sub_department": "Enterprise Sales",
        "designation_name": "Senior Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1300000,
        "reporting_manager_code": "IPP-011",
        "pan": "DDDHS0000D",
        "bank_name": "Kotak Bank", "bank_account_no": "63099900030", "bank_ifsc": "KKBK0000002",
        "qualification": "MBA", "institute": "NMIMS Mumbai", "specialization": "Marketing & Sales",
        "year_of_passing": 2017, "previous_employer": "Nucleus Software", "experience_years": 7,
        "domain": "Enterprise SaaS Sales", "skills": "Enterprise Prospecting, Demo, Proposal, Negotiation, HCM",
        "certifications": "",
        "emergency_contact_name": "Rekha Sharma", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-9000000130",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "hemanth.s@gmail.com", "personal_phone": "+91-9100000030",
        "current_address": "Flat 201, Indiranagar, Bengaluru 560038",
        "permanent_address": "12-6, Jaipur 302001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-031",
        "first_name": "Deepa", "last_name": "Krishnamurti",
        "work_email": "deepa.krishnamurti@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000031", "gender": "Female",
        "date_of_birth": datetime.date(1993, 9, 4),
        "date_of_joining": datetime.date(2023, 6, 5),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "PROD",
        "sub_department": "Payroll & Finance",
        "designation_name": "Executive",
        "team": "Product", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 1500000,
        "reporting_manager_code": "IPP-010",
        "pan": "EEEXK1000E",
        "bank_name": "SBI", "bank_account_no": "30099900031", "bank_ifsc": "SBIN0000008",
        "qualification": "B.Tech + MBA", "institute": "PSG Tech / ISB", "specialization": "Product Management",
        "year_of_passing": 2016, "previous_employer": "Greytip Software", "experience_years": 7,
        "domain": "Payroll Product", "skills": "Payroll Domain, Tax Rules, Product Design, User Stories, Jira",
        "certifications": "",
        "emergency_contact_name": "Krishna Murti", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000131",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "deepa.km@gmail.com", "personal_phone": "+91-9100000031",
        "current_address": "Flat 401, Madhapur, Hyderabad 500081",
        "permanent_address": "23-4, Coimbatore 641002",
        "password": "123456",
    },
    {
        "employee_code": "IPP-032",
        "first_name": "Naveen", "last_name": "Raj",
        "work_email": "naveen.raj@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000032", "gender": "Male",
        "date_of_birth": datetime.date(1996, 6, 18),
        "date_of_joining": datetime.date(2023, 5, 22),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "CS",
        "sub_department": "Support Engineering",
        "designation_name": "Executive",
        "team": "Customer Success", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 1000000,
        "reporting_manager_code": "IPP-016",
        "pan": "FFFNR2000F",
        "bank_name": "ICICI Bank", "bank_account_no": "02699900032", "bank_ifsc": "ICIC0000006",
        "qualification": "B.Tech", "institute": "RVCE Bengaluru", "specialization": "Information Science",
        "year_of_passing": 2018, "previous_employer": "Mindtree", "experience_years": 5,
        "domain": "Technical Support", "skills": "HCM APIs, SQL Debugging, REST, Postman, Ticket Resolution",
        "certifications": "ITIL Foundation",
        "emergency_contact_name": "Suresh Raj", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000132",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "naveen.raj@gmail.com", "personal_phone": "+91-9100000032",
        "current_address": "PG, BTM Layout, Bengaluru 560076",
        "permanent_address": "5-6, Madurai 625020",
        "password": "123456",
    },
    {
        "employee_code": "IPP-033",
        "first_name": "Bhavana", "last_name": "Nair",
        "work_email": "bhavana.nair@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000033", "gender": "Female",
        "date_of_birth": datetime.date(1992, 2, 11),
        "date_of_joining": datetime.date(2022, 12, 5),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "QA & Automation",
        "designation_name": "Senior Engineer",
        "team": "Engineering", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 1200000,
        "reporting_manager_code": "IPP-017",
        "pan": "GGGXN3000G",
        "bank_name": "Axis Bank", "bank_account_no": "91599900033", "bank_ifsc": "UTIB0000007",
        "qualification": "B.Tech", "institute": "CUSAT Kochi", "specialization": "Computer Science",
        "year_of_passing": 2014, "previous_employer": "UST Global", "experience_years": 10,
        "domain": "QA Engineering", "skills": "Selenium, Playwright, API Testing, JIRA, BDD, TestNG",
        "certifications": "ISTQB Advanced Test Analyst",
        "emergency_contact_name": "Rajan Nair", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-9000000133",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "bhavana.nair@gmail.com", "personal_phone": "+91-9100000033",
        "current_address": "Flat 404, Hitech City, Hyderabad 500081",
        "permanent_address": "TC 6-78, Kochi 682007",
        "password": "123456",
    },
    {
        "employee_code": "IPP-034",
        "first_name": "Rohan", "last_name": "Patil",
        "work_email": "rohan.patil@impacgopeople.com",
        "role_name": "Professional / IC Employee",
        "phone": "+91-9000000034", "gender": "Male",
        "date_of_birth": datetime.date(1995, 11, 3),
        "date_of_joining": datetime.date(2023, 7, 10),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "SALES",
        "sub_department": "SMB Sales",
        "designation_name": "Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 6,
        "annual_ctc": 900000,
        "reporting_manager_code": "IPP-011",
        "pan": "HHHXP4000H",
        "bank_name": "SBI", "bank_account_no": "30099900034", "bank_ifsc": "SBIN0000009",
        "qualification": "MBA", "institute": "Symbiosis Pune", "specialization": "Marketing",
        "year_of_passing": 2018, "previous_employer": "Paytm", "experience_years": 5,
        "domain": "SaaS SMB Sales", "skills": "Outbound Sales, Demo, Objection Handling, CRM, HubSpot",
        "certifications": "",
        "emergency_contact_name": "Suresh Patil", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000134",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "rohan.patil@gmail.com", "personal_phone": "+91-9100000034",
        "current_address": "PG, Koramangala, Bengaluru 560095",
        "permanent_address": "12-3, Kolhapur 416001",
        "password": "123456",
    },
    # ── Associate / Intern ────────────────────────────────────────────────
    {
        "employee_code": "IPP-035",
        "first_name": "Sai Kiran", "last_name": "Goud",
        "work_email": "saikiran.goud@impacgopeople.com",
        "role_name": "Associate / Intern",
        "phone": "+91-9000000035", "gender": "Male",
        "date_of_birth": datetime.date(2001, 4, 14),
        "date_of_joining": datetime.date(2024, 6, 3),
        "employment_type": "Intern", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Frontend",
        "designation_name": "Intern",
        "team": "Engineering", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 240000,
        "reporting_manager_code": "IPP-014",
        "pan": "IIIXG5000I",
        "bank_name": "SBI", "bank_account_no": "30099900035", "bank_ifsc": "SBIN0000010",
        "qualification": "B.Tech (Pursuing)", "institute": "JNTU Hyderabad", "specialization": "Computer Science",
        "year_of_passing": 2025, "previous_employer": None, "experience_years": 0,
        "domain": "Flutter", "skills": "Flutter, Dart, Basic REST APIs",
        "certifications": "",
        "emergency_contact_name": "Ramaiah Goud", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000135",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "saikiran.goud@gmail.com", "personal_phone": "+91-9100000035",
        "current_address": "Hostel, JNTU Kukatpally, Hyderabad 500072",
        "permanent_address": "H.No 2-3, Nalgonda 508001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-036",
        "first_name": "Keerthi", "last_name": "Prasad",
        "work_email": "keerthi.prasad@impacgopeople.com",
        "role_name": "Associate / Intern",
        "phone": "+91-9000000036", "gender": "Female",
        "date_of_birth": datetime.date(2001, 8, 30),
        "date_of_joining": datetime.date(2024, 6, 3),
        "employment_type": "Intern", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "PROD",
        "sub_department": "Core HCM",
        "designation_name": "Intern",
        "team": "Product", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 240000,
        "reporting_manager_code": "IPP-010",
        "pan": "JJJKP6000J",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900036", "bank_ifsc": "HDFC0000010",
        "qualification": "MBA (Pursuing)", "institute": "IIM Shillong", "specialization": "Product Management",
        "year_of_passing": 2025, "previous_employer": None, "experience_years": 0,
        "domain": "Product Management", "skills": "Wireframing, User Stories, Jira, Figma basics",
        "certifications": "",
        "emergency_contact_name": "Latha Prasad", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-9000000136",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "keerthi.prasad@gmail.com", "personal_phone": "+91-9100000036",
        "current_address": "PG, Madhapur, Hyderabad 500081",
        "permanent_address": "H.No 7-4, Warangal 506001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-037",
        "first_name": "Arjun", "last_name": "Verma",
        "work_email": "arjun.verma@impacgopeople.com",
        "role_name": "Associate / Intern",
        "phone": "+91-9000000037", "gender": "Male",
        "date_of_birth": datetime.date(2000, 12, 7),
        "date_of_joining": datetime.date(2024, 1, 8),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-HYD", "department_code": "ENGG",
        "sub_department": "Backend",
        "designation_name": "Junior Engineer",
        "team": "Engineering", "work_mode": "Hybrid", "numeric_band": 7,
        "annual_ctc": 480000,
        "reporting_manager_code": "IPP-015",
        "pan": "KKKXV7000K",
        "bank_name": "Axis Bank", "bank_account_no": "91599900037", "bank_ifsc": "UTIB0000008",
        "qualification": "B.Tech", "institute": "Andhra University", "specialization": "Computer Science",
        "year_of_passing": 2023, "previous_employer": None, "experience_years": 1,
        "domain": "Python / Backend", "skills": "Python, FastAPI, PostgreSQL, Git, Linux basics",
        "certifications": "",
        "emergency_contact_name": "Suresh Verma", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000137",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "arjun.verma@gmail.com", "personal_phone": "+91-9100000037",
        "current_address": "PG, Kondapur, Hyderabad 500084",
        "permanent_address": "H.No 3-5, Vijayawada 520001",
        "password": "123456",
    },
    {
        "employee_code": "IPP-038",
        "first_name": "Meghana", "last_name": "Rao",
        "work_email": "meghana.rao@impacgopeople.com",
        "role_name": "Associate / Intern",
        "phone": "+91-9000000038", "gender": "Female",
        "date_of_birth": datetime.date(2001, 2, 18),
        "date_of_joining": datetime.date(2024, 6, 3),
        "employment_type": "Intern", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "CS",
        "sub_department": "Onboarding",
        "designation_name": "Intern",
        "team": "Customer Success", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 240000,
        "reporting_manager_code": "IPP-012",
        "pan": "LLLXR8000L",
        "bank_name": "SBI", "bank_account_no": "30099900038", "bank_ifsc": "SBIN0000011",
        "qualification": "MBA (Pursuing)", "institute": "IFIM Bengaluru", "specialization": "Marketing",
        "year_of_passing": 2025, "previous_employer": None, "experience_years": 0,
        "domain": "Customer Success", "skills": "Communication, HCM Basics, Excel, Customer Interaction",
        "certifications": "",
        "emergency_contact_name": "Venkat Rao", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000138",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "meghana.rao@gmail.com", "personal_phone": "+91-9100000038",
        "current_address": "PG, BTM Layout, Bengaluru 560029",
        "permanent_address": "H.No 5-8, Tirupati 517501",
        "password": "123456",
    },
    {
        "employee_code": "IPP-039",
        "first_name": "Tarun", "last_name": "Singh",
        "work_email": "tarun.singh@impacgopeople.com",
        "role_name": "Associate / Intern",
        "phone": "+91-9000000039", "gender": "Male",
        "date_of_birth": datetime.date(2000, 9, 25),
        "date_of_joining": datetime.date(2024, 2, 19),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPP-BLR", "department_code": "SALES",
        "sub_department": "Partnerships",
        "designation_name": "Junior Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 7,
        "annual_ctc": 420000,
        "reporting_manager_code": "IPP-011",
        "pan": "MMXXS9000M",
        "bank_name": "HDFC Bank", "bank_account_no": "50099900039", "bank_ifsc": "HDFC0000011",
        "qualification": "BBA", "institute": "Christ University Bengaluru", "specialization": "Marketing",
        "year_of_passing": 2023, "previous_employer": None, "experience_years": 1,
        "domain": "Sales Operations", "skills": "Lead Generation, CRM, Excel, LinkedIn Sales Navigator",
        "certifications": "",
        "emergency_contact_name": "Rakesh Singh", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-9000000139",
        "blood_group": "A-", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "tarun.singh@gmail.com", "personal_phone": "+91-9100000039",
        "current_address": "PG, Koramangala, Bengaluru 560034",
        "permanent_address": "H.No 4-5, Lucknow 226001",
        "password": "123456",
    },
]

QUICK_LOGIN_BY_ROLE = {
    "Organization Owner / CEO":      EMPLOYEES[0],   # IPP-001
    "C-Level Executive":             EMPLOYEES[1],   # IPP-002
    "VP / Director":                 EMPLOYEES[3],   # IPP-004
    "General Manager / Sr. Manager": EMPLOYEES[5],   # IPP-006
    "Manager":                       EMPLOYEES[8],   # IPP-009
    "Team Lead":                     EMPLOYEES[13],  # IPP-014
    "HR / Recruitment Staff":        EMPLOYEES[17],  # IPP-018
    "Finance / Payroll Staff":       EMPLOYEES[20],  # IPP-021
    "IT / System Admin":             EMPLOYEES[22],  # IPP-023
    "Professional / IC Employee":    EMPLOYEES[24],  # IPP-025
    "Associate / Intern":            EMPLOYEES[34],  # IPP-035
}
