"""Seed data for Impacgo solutions Private Limited (ERP demo company)."""

import datetime

COMPANY_NAME = "Impacgo solutions Private Limited"
COMPANY_ID   = "caf06078-29da-4817-a26a-1f019fe083c7"
EMAIL_DOMAIN = "impacgo.com"

# ── Branches ──────────────────────────────────────────────────────────────────

BRANCHES = [
    {"code": "IPG-VZG", "name": "Visakhapatnam HQ",  "country": "India", "state": "Andhra Pradesh", "city": "Visakhapatnam", "tax": "37AABCM4521Q1Z8", "is_head_office": True},
    {"code": "IPG-HYD", "name": "Hyderabad Office",  "country": "India", "state": "Telangana",       "city": "Hyderabad",      "tax": "36AABCM4521Q1Z9", "is_head_office": False},
]

# ── Business units ────────────────────────────────────────────────────────────

BUSINESS_UNITS = [
    {"name": "Administration",              "cost_center": "CC-IPG-100"},
    {"name": "Finance & Accounts",          "cost_center": "CC-IPG-200"},
    {"name": "Sales & Marketing",           "cost_center": "CC-IPG-300"},
    {"name": "Operations & Manufacturing",  "cost_center": "CC-IPG-400"},
    # -- Added from impacgo-website content: real D365 services + in-house
    # product lines, distinct from the generic manufacturing units above.
    {"name": "Dynamics 365 Services",       "cost_center": "CC-IPG-500"},
    {"name": "Product Engineering",         "cost_center": "CC-IPG-600"},
]

# ── Departments ───────────────────────────────────────────────────────────────

DEPARTMENTS = [
    {"code": "EXO", "name": "Executive Office",       "business_unit_name": "Administration",             "branch_code": "IPG-VZG",
     "subs": ["Management", "Corporate Affairs"],                                                           "annual_budget": 20_000_000},
    {"code": "HR",  "name": "Human Resources",        "business_unit_name": "Administration",             "branch_code": "IPG-VZG",
     "subs": ["Talent Acquisition", "HR Operations", "Payroll & Benefits"],                                "annual_budget": 15_000_000},
    {"code": "FIN", "name": "Finance & Accounts",     "business_unit_name": "Finance & Accounts",         "branch_code": "IPG-VZG",
     "subs": ["Accounting", "Payroll", "Audit & Compliance"],                                              "annual_budget": 18_000_000},
    {"code": "SLS", "name": "Sales & Marketing",      "business_unit_name": "Sales & Marketing",          "branch_code": "IPG-HYD",
     "subs": ["Domestic Sales", "Export Sales", "Digital Marketing"],                                     "annual_budget": 30_000_000},
    {"code": "PCR", "name": "Procurement",            "business_unit_name": "Operations & Manufacturing", "branch_code": "IPG-VZG",
     "subs": ["Vendor Management", "Purchase Operations"],                                                 "annual_budget": 12_000_000},
    {"code": "WHS", "name": "Warehouse & Logistics",  "business_unit_name": "Operations & Manufacturing", "branch_code": "IPG-VZG",
     "subs": ["Inbound", "Outbound", "Inventory Control"],                                                 "annual_budget": 10_000_000},
    {"code": "MFG", "name": "Manufacturing",          "business_unit_name": "Operations & Manufacturing", "branch_code": "IPG-VZG",
     "subs": ["Production Line A", "Production Line B", "Assembly"],                                      "annual_budget": 40_000_000},
    {"code": "QC",  "name": "Quality Control",        "business_unit_name": "Operations & Manufacturing", "branch_code": "IPG-VZG",
     "subs": ["Incoming QC", "In-Process QC", "Final Inspection"],                                        "annual_budget": 8_000_000},
    {"code": "IT",  "name": "Information Technology", "business_unit_name": "Administration",             "branch_code": "IPG-HYD",
     "subs": ["Infrastructure", "IT Support", "ERP Systems"],                                             "annual_budget": 12_000_000},
    {"code": "CRM", "name": "Customer Relations",     "business_unit_name": "Sales & Marketing",          "branch_code": "IPG-HYD",
     "subs": ["Customer Support", "Account Management"],                                                  "annual_budget": 8_000_000},

    # -- Added from impacgo-website content (services + product suite).
    # All kept on branch_code IPG-VZG (Visakhapatnam HQ) -- the branch
    # record itself is untouched, these just attach to it via FK.
    {"code": "D365",    "name": "Dynamics 365 Practice",    "business_unit_name": "Dynamics 365 Services", "branch_code": "IPG-VZG",
     "subs": ["D365 Implementation", "D365 Development & Enhancement", "Application Management Services (AMS)", "D365 Consulting"],
     "annual_budget": 25_000_000},
    {"code": "PPAI",    "name": "Power Platform & AI",      "business_unit_name": "Dynamics 365 Services", "branch_code": "IPG-VZG",
     "subs": ["Power BI", "Power Apps", "Power Automate", "AI Automation & Copilot"],
     "annual_budget": 12_000_000},
    {"code": "MIGINT",  "name": "Migration & Integrations", "business_unit_name": "Dynamics 365 Services", "branch_code": "IPG-VZG",
     "subs": ["AX to D365 Migration", "Third-Party Integrations", "MES Integration"],
     "annual_budget": 10_000_000},
    {"code": "PRDENG",  "name": "Product Engineering",      "business_unit_name": "Product Engineering",   "branch_code": "IPG-VZG",
     "subs": ["Impacgo ERP Suite Engineering", "Platform & QA"],
     "annual_budget": 35_000_000},
    {"code": "SAASPD",  "name": "SaaS Products",            "business_unit_name": "Product Engineering",   "branch_code": "IPG-VZG",
     "subs": ["CALVIQ – Dairy Farm Management", "StockLyte – Inventory Management", "FarmYieldIQ", "HealthVault – Family Health Records", "Work Task & Construction Planner"],
     "annual_budget": 20_000_000},
]

# ── Projects ──────────────────────────────────────────────────────────────────
# Added from impacgo-website content: real named clients (HomePage.jsx
# ClientLogosSection) for D365 engagements, and the site's own in-house
# ERP suite (erpModules.js) + standalone SaaS products as internal
# products. status values match pm_projects: draft|planning|active|
# on_hold|completed|cancelled.

IMPACGO_PROJECTS = [
    # -- Client engagements (Dynamics 365 Practice, billable) --
    # "code" is explicit (not auto-derived) -- crud.create_project's default
    # code generation truncates to the first 10 alnum chars of the name,
    # which collapsed every "D365 F&O Implementation — <client>" project to
    # the same "D365FOIMPL" code and crashed the insert (see incident: only
    # Resonac made it in before the duplicate-key error killed the run).
    {"name": "D365 F&O Implementation — Resonac", "client_name": "Resonac", "code": "RESONAC-D365",
     "category_name": "D365 Implementation", "department_code": "D365",
     "status": "completed", "is_billable": True,
     "planned_start_date": "2024-01-15", "planned_end_date": "2024-09-30"},
    {"name": "D365 F&O Implementation — Hitachi", "client_name": "Hitachi", "code": "HITACHI-D365",
     "category_name": "D365 Implementation", "department_code": "D365",
     "status": "completed", "is_billable": True,
     "planned_start_date": "2023-06-01", "planned_end_date": "2024-02-28"},
    {"name": "D365 F&O Rollout — Ironing Boy", "client_name": "Ironing Boy", "code": "IRNBOY-D365",
     "category_name": "D365 Implementation", "department_code": "D365",
     "status": "active", "is_billable": True,
     "planned_start_date": "2025-11-01", "planned_end_date": "2026-10-31"},
    {"name": "D365 Development & AMS — Perfect Model Solutions", "client_name": "Perfect Model Solutions", "code": "PMS-AMS",
     "category_name": "Application Management Services (AMS)", "department_code": "D365",
     "status": "active", "is_billable": True,
     "planned_start_date": "2025-04-01", "planned_end_date": "2026-12-31"},
    {"name": "D365 Platform Support — ETOR", "client_name": "ETOR", "code": "ETOR-AMS",
     "category_name": "Application Management Services (AMS)", "department_code": "D365",
     "status": "active", "is_billable": True,
     "planned_start_date": "2025-01-01", "planned_end_date": "2026-12-31"},
    {"name": "D365 F&O Implementation — Rosti", "client_name": "Rosti", "code": "ROSTI-D365",
     "category_name": "D365 Implementation", "department_code": "D365",
     "status": "completed", "is_billable": True,
     "planned_start_date": "2023-02-01", "planned_end_date": "2023-11-30"},
    {"name": "D365 Development — Daxonet", "client_name": "Daxonet", "code": "DAXONET-DEV",
     "category_name": "D365 Development & Enhancement", "department_code": "D365",
     "status": "active", "is_billable": True,
     "planned_start_date": "2026-02-01", "planned_end_date": "2026-12-31"},

    # -- Internal products: Impacgo ERP Suite (Product Engineering, non-billable) --
    {"name": "Impacgo HRMS", "client_name": "Internal Product", "code": "IPG-ERP-HRMS",
     "category_name": "ERP Product", "department_code": "PRDENG",
     "status": "planning", "is_billable": False,
     "planned_start_date": "2025-06-01", "planned_end_date": "2026-12-31"},
    {"name": "Impacgo Finance", "client_name": "Internal Product", "code": "IPG-ERP-FIN",
     "category_name": "ERP Product", "department_code": "PRDENG",
     "status": "planning", "is_billable": False,
     "planned_start_date": "2025-08-01", "planned_end_date": "2027-03-31"},
    {"name": "Impacgo Chain", "client_name": "Internal Product", "code": "IPG-ERP-CHAIN",
     "category_name": "ERP Product", "department_code": "PRDENG",
     "status": "active", "is_billable": False,
     "planned_start_date": "2025-01-01", "planned_end_date": "2026-12-31"},
    {"name": "Impacgo Make", "client_name": "Internal Product", "code": "IPG-ERP-MAKE",
     "category_name": "ERP Product", "department_code": "PRDENG",
     "status": "planning", "is_billable": False,
     "planned_start_date": "2025-09-01", "planned_end_date": "2027-01-31"},
    {"name": "Impacgo Plan", "client_name": "Internal Product", "code": "IPG-ERP-PLAN",
     "category_name": "ERP Product", "department_code": "PRDENG",
     "status": "planning", "is_billable": False,
     "planned_start_date": "2025-10-01", "planned_end_date": "2027-02-28"},
    {"name": "Impacgo Retail", "client_name": "Internal Product", "code": "IPG-ERP-RETAIL",
     "category_name": "ERP Product", "department_code": "PRDENG",
     "status": "planning", "is_billable": False,
     "planned_start_date": "2025-07-01", "planned_end_date": "2026-12-31"},
    {"name": "Impacgo Project", "client_name": "Internal Product", "code": "IPG-ERP-PRJ",
     "category_name": "ERP Product", "department_code": "PRDENG",
     "status": "planning", "is_billable": False,
     "planned_start_date": "2025-11-01", "planned_end_date": "2027-01-31"},

    # -- Internal products: standalone SaaS products (SaaS Products dept, non-billable) --
    {"name": "CALVIQ – Dairy Farm Management", "client_name": "Internal Product", "code": "SAAS-CALVIQ",
     "category_name": "SaaS Product", "department_code": "SAASPD",
     "status": "active", "is_billable": False,
     "planned_start_date": "2024-06-01", "planned_end_date": None},
    {"name": "StockLyte – Inventory Management", "client_name": "Internal Product", "code": "SAAS-STOCKLYTE",
     "category_name": "SaaS Product", "department_code": "SAASPD",
     "status": "active", "is_billable": False,
     "planned_start_date": "2024-09-01", "planned_end_date": None},
    {"name": "FarmYieldIQ", "client_name": "Internal Product", "code": "SAAS-FARMYIELDIQ",
     "category_name": "SaaS Product", "department_code": "SAASPD",
     "status": "active", "is_billable": False,
     "planned_start_date": "2025-02-01", "planned_end_date": None},
    {"name": "HealthVault – Family Health Records", "client_name": "Internal Product", "code": "SAAS-HEALTHVAULT",
     "category_name": "SaaS Product", "department_code": "SAASPD",
     "status": "active", "is_billable": False,
     "planned_start_date": "2025-03-01", "planned_end_date": None},
    {"name": "Work Task Application", "client_name": "Internal Product", "code": "SAAS-WORKTASK",
     "category_name": "SaaS Product", "department_code": "SAASPD",
     "status": "active", "is_billable": False,
     "planned_start_date": "2024-03-01", "planned_end_date": None},
    {"name": "Construction Planner", "client_name": "Internal Product", "code": "SAAS-CONSTPLAN",
     "category_name": "SaaS Product", "department_code": "SAASPD",
     "status": "active", "is_billable": False,
     "planned_start_date": "2024-11-01", "planned_end_date": None},
]

# ── Employees ─────────────────────────────────────────────────────────────────
# Fields match what crud.create_employee / seed_new_company.ensure_employees expect.

EMPLOYEES = [
    # ── Executive (1) ──────────────────────────────────────────────────────
    {
        "employee_code": "IPG-001",
        "first_name": "Narasimha", "last_name": "Reddy",
        "work_email": "narasimha.reddy@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345001", "gender": "Male",
        "date_of_birth": datetime.date(1974, 3, 15),
        "date_of_joining": datetime.date(2014, 4, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "EXO",
        "sub_department": "Management",
        "designation_name": "Managing Director",
        "team": "Leadership", "work_mode": "On-site", "numeric_band": 1,
        "annual_ctc": 5000000,
        "reporting_manager_code": None,
        "pan": "AABPR1234A",
        "bank_name": "State Bank of India", "bank_account_no": "30012345001", "bank_ifsc": "SBIN0001234",
        "qualification": "MBA", "institute": "IIM Ahmedabad", "specialization": "General Management",
        "year_of_passing": 1998, "previous_employer": "Infosys Ltd", "experience_years": 22,
        "domain": "General Management", "skills": "Leadership, Strategy, P&L",
        "certifications": "PMP",
        "emergency_contact_name": "Seetha Reddy", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345101",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "narasimha.r@gmail.com", "personal_phone": "+91-9912345001",
        "current_address": "Guptha Villa, Vip Road, Visakhapatnam 530003",
        "permanent_address": "Guptha Villa, Vip Road, Visakhapatnam 530003",
        "password": "123456",
    },
    # ── IT / System Administrator (1) ─────────────────────────────────────
    {
        "employee_code": "IPG-002",
        "first_name": "Venkata", "last_name": "Subrahmanyam",
        "work_email": "venkata.subrahmanyam@impacgo.com",
        "role_name": "System Administrator",
        "phone": "+91-8912345002", "gender": "Male",
        "date_of_birth": datetime.date(1988, 7, 22),
        "date_of_joining": datetime.date(2017, 9, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "IT",
        "sub_department": "ERP Systems",
        "designation_name": "Senior Manager",
        "team": "IT", "work_mode": "On-site", "numeric_band": 4,
        "annual_ctc": 1800000,
        "reporting_manager_code": "IPG-001",
        "pan": "BBBVS2345B",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345002", "bank_ifsc": "HDFC0001234",
        "qualification": "B.Tech", "institute": "JNTU Hyderabad", "specialization": "Computer Science",
        "year_of_passing": 2010, "previous_employer": "Wipro Technologies", "experience_years": 14,
        "domain": "ERP & IT Administration", "skills": "SAP, Oracle ERP, Linux, Networking",
        "certifications": "MCSA, ITIL",
        "emergency_contact_name": "Anitha Subrahmanyam", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345102",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "venkata.sub@gmail.com", "personal_phone": "+91-9012345002",
        "current_address": "Flat 4B, Cyber Towers, Madhapur, Hyderabad 500081",
        "permanent_address": "12-3, Srinagar Colony, Visakhapatnam 530044",
        "password": "123456",
    },
    # ── HR Manager (1) ────────────────────────────────────────────────────
    {
        "employee_code": "IPG-003",
        "first_name": "Meena", "last_name": "Sharma",
        "work_email": "meena.sharma@impacgo.com",
        "role_name": "HR Manager",
        "phone": "+91-8912345003", "gender": "Female",
        "date_of_birth": datetime.date(1982, 11, 5),
        "date_of_joining": datetime.date(2016, 6, 15),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "HR",
        "sub_department": "HR Operations",
        "designation_name": "Manager",
        "team": "HR", "work_mode": "On-site", "numeric_band": 4,
        "annual_ctc": 1400000,
        "reporting_manager_code": "IPG-001",
        "pan": "CCCMS3456C",
        "bank_name": "ICICI Bank", "bank_account_no": "02612345003", "bank_ifsc": "ICIC0001234",
        "qualification": "MBA HR", "institute": "Osmania University", "specialization": "Human Resources",
        "year_of_passing": 2005, "previous_employer": "HCL Technologies", "experience_years": 19,
        "domain": "Human Resources", "skills": "Talent Acquisition, HRIS, Compliance, Payroll",
        "certifications": "SHRM-CP",
        "emergency_contact_name": "Ravi Sharma", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345103",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "meena.sharma@gmail.com", "personal_phone": "+91-9012345003",
        "current_address": "Plot 15, MVP Colony, Visakhapatnam 530017",
        "permanent_address": "Plot 15, MVP Colony, Visakhapatnam 530017",
        "password": "123456",
    },
    # ── HR Executive (2) ──────────────────────────────────────────────────
    {
        "employee_code": "IPG-004",
        "first_name": "Sai Kiran", "last_name": "Prasad",
        "work_email": "saikiran.prasad@impacgo.com",
        "role_name": "HR Executive",
        "phone": "+91-8912345004", "gender": "Male",
        "date_of_birth": datetime.date(1994, 2, 18),
        "date_of_joining": datetime.date(2019, 3, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "HR",
        "sub_department": "Talent Acquisition",
        "designation_name": "Executive",
        "team": "HR", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 600000,
        "reporting_manager_code": "IPG-003",
        "pan": "DDDSP4567D",
        "bank_name": "Axis Bank", "bank_account_no": "91512345004", "bank_ifsc": "UTIB0001234",
        "qualification": "MBA HR", "institute": "Andhra University", "specialization": "HR Management",
        "year_of_passing": 2016, "previous_employer": "Mphasis", "experience_years": 7,
        "domain": "Talent Acquisition", "skills": "Recruitment, Onboarding, HRMS",
        "certifications": "",
        "emergency_contact_name": "Lakshmi Prasad", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-8912345104",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "saikiran.p@gmail.com", "personal_phone": "+91-9012345004",
        "current_address": "H.No 7-12, Lawsons Bay Colony, Visakhapatnam 530017",
        "permanent_address": "H.No 7-12, Lawsons Bay Colony, Visakhapatnam 530017",
        "password": "123456",
    },
    {
        "employee_code": "IPG-005",
        "first_name": "Divya", "last_name": "Kumari",
        "work_email": "divya.kumari@impacgo.com",
        "role_name": "HR Executive",
        "phone": "+91-8912345005", "gender": "Female",
        "date_of_birth": datetime.date(1996, 8, 30),
        "date_of_joining": datetime.date(2021, 1, 10),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "HR",
        "sub_department": "HR Operations",
        "designation_name": "Executive",
        "team": "HR", "work_mode": "Hybrid", "numeric_band": 6,
        "annual_ctc": 550000,
        "reporting_manager_code": "IPG-003",
        "pan": "EEECK5678E",
        "bank_name": "SBI", "bank_account_no": "30012345005", "bank_ifsc": "SBIN0002345",
        "qualification": "B.A. Psychology", "institute": "Andhra University", "specialization": "HR",
        "year_of_passing": 2018, "previous_employer": "Tech Mahindra", "experience_years": 5,
        "domain": "HR Operations", "skills": "Payroll, Compliance, Employee Engagement",
        "certifications": "",
        "emergency_contact_name": "Suresh Kumari", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345105",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "divya.k@gmail.com", "personal_phone": "+91-9012345005",
        "current_address": "Flat 201, Ashok Nagar, Hyderabad 500020",
        "permanent_address": "12-4, Gandhi Nagar, Visakhapatnam 530020",
        "password": "123456",
    },
    # ── Finance Manager (1) ───────────────────────────────────────────────
    {
        "employee_code": "IPG-006",
        "first_name": "Subrahmanyam", "last_name": "Iyer",
        "work_email": "subrahmanyam.iyer@impacgo.com",
        "role_name": "Finance Manager",
        "phone": "+91-8912345006", "gender": "Male",
        "date_of_birth": datetime.date(1979, 5, 12),
        "date_of_joining": datetime.date(2015, 8, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "FIN",
        "sub_department": "Accounting",
        "designation_name": "Manager",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 4,
        "annual_ctc": 1600000,
        "reporting_manager_code": "IPG-001",
        "pan": "FFFSI6789F",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345006", "bank_ifsc": "HDFC0002345",
        "qualification": "CA", "institute": "ICAI", "specialization": "Finance & Accounts",
        "year_of_passing": 2003, "previous_employer": "Deloitte India", "experience_years": 21,
        "domain": "Finance & Accounts", "skills": "Financial Reporting, Taxation, Budgeting, ERP Finance",
        "certifications": "CA, CMA",
        "emergency_contact_name": "Vimala Iyer", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345106",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "subrahmanyam.i@gmail.com", "personal_phone": "+91-9012345006",
        "current_address": "8-1, Seethammadhara, Visakhapatnam 530013",
        "permanent_address": "8-1, Seethammadhara, Visakhapatnam 530013",
        "password": "123456",
    },
    # ── Accountant (2) ────────────────────────────────────────────────────
    {
        "employee_code": "IPG-007",
        "first_name": "Kavitha", "last_name": "Nair",
        "work_email": "kavitha.nair@impacgo.com",
        "role_name": "Accountant",
        "phone": "+91-8912345007", "gender": "Female",
        "date_of_birth": datetime.date(1990, 3, 25),
        "date_of_joining": datetime.date(2018, 4, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "FIN",
        "sub_department": "Accounting",
        "designation_name": "Senior Executive",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 800000,
        "reporting_manager_code": "IPG-006",
        "pan": "GGGKN7890G",
        "bank_name": "ICICI Bank", "bank_account_no": "02612345007", "bank_ifsc": "ICIC0002345",
        "qualification": "B.Com", "institute": "Andhra University", "specialization": "Accounting",
        "year_of_passing": 2012, "previous_employer": "Grant Thornton", "experience_years": 12,
        "domain": "Accounts & Finance", "skills": "Tally, GST, TDS, Accounts Payable/Receivable",
        "certifications": "CMA Inter",
        "emergency_contact_name": "Rajan Nair", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345107",
        "blood_group": "AB+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "kavitha.nair@gmail.com", "personal_phone": "+91-9012345007",
        "current_address": "Flat 302, Sun Avenue, Siripuram, Visakhapatnam 530003",
        "permanent_address": "TC 12-34, Trivandrum 695004",
        "password": "123456",
    },
    {
        "employee_code": "IPG-008",
        "first_name": "Rajesh", "last_name": "Kumar",
        "work_email": "rajesh.kumar@impacgo.com",
        "role_name": "Accountant",
        "phone": "+91-8912345008", "gender": "Male",
        "date_of_birth": datetime.date(1992, 9, 14),
        "date_of_joining": datetime.date(2019, 7, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "FIN",
        "sub_department": "Accounting",
        "designation_name": "Executive",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 650000,
        "reporting_manager_code": "IPG-006",
        "pan": "HHHRK8901H",
        "bank_name": "Canara Bank", "bank_account_no": "12312345008", "bank_ifsc": "CNRB0001234",
        "qualification": "M.Com", "institute": "Nagarjuna University", "specialization": "Accounting",
        "year_of_passing": 2015, "previous_employer": "KPMG India", "experience_years": 9,
        "domain": "Accounts", "skills": "Tally, SAP FICO, GST, Income Tax",
        "certifications": "",
        "emergency_contact_name": "Sunita Kumar", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-8912345108",
        "blood_group": "O-", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "rajesh.k@gmail.com", "personal_phone": "+91-9012345008",
        "current_address": "H.No 4-56, Dwaraka Nagar, Visakhapatnam 530016",
        "permanent_address": "H.No 4-56, Dwaraka Nagar, Visakhapatnam 530016",
        "password": "123456",
    },
    # ── Payroll Officer (1) ───────────────────────────────────────────────
    {
        "employee_code": "IPG-009",
        "first_name": "Padmavathi", "last_name": "Srinivas",
        "work_email": "padmavathi.srinivas@impacgo.com",
        "role_name": "Payroll Officer",
        "phone": "+91-8912345009", "gender": "Female",
        "date_of_birth": datetime.date(1985, 6, 20),
        "date_of_joining": datetime.date(2017, 2, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "FIN",
        "sub_department": "Payroll",
        "designation_name": "Senior Executive",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 720000,
        "reporting_manager_code": "IPG-006",
        "pan": "IIIPS9012I",
        "bank_name": "SBI", "bank_account_no": "30012345009", "bank_ifsc": "SBIN0003456",
        "qualification": "B.Com", "institute": "Andhra University", "specialization": "Commerce",
        "year_of_passing": 2007, "previous_employer": "ADP India", "experience_years": 17,
        "domain": "Payroll Management", "skills": "Payroll Processing, PF, ESI, PT, TDS",
        "certifications": "Certified Payroll Professional",
        "emergency_contact_name": "Srinivas Rao", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345109",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "padmavathi.s@gmail.com", "personal_phone": "+91-9012345009",
        "current_address": "Plot 22, Madhura Nagar, Visakhapatnam 530007",
        "permanent_address": "Plot 22, Madhura Nagar, Visakhapatnam 530007",
        "password": "123456",
    },
    # ── Auditor Read Only (1) ─────────────────────────────────────────────
    {
        "employee_code": "IPG-010",
        "first_name": "Chandrasekar", "last_name": "Aiyer",
        "work_email": "chandrasekar.aiyer@impacgo.com",
        "role_name": "Auditor (Read Only)",
        "phone": "+91-8912345010", "gender": "Male",
        "date_of_birth": datetime.date(1977, 4, 8),
        "date_of_joining": datetime.date(2018, 11, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "FIN",
        "sub_department": "Audit & Compliance",
        "designation_name": "Senior Manager",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 4,
        "annual_ctc": 1200000,
        "reporting_manager_code": "IPG-006",
        "pan": "JJJCA0123J",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345010", "bank_ifsc": "HDFC0003456",
        "qualification": "CA", "institute": "ICAI", "specialization": "Audit & Taxation",
        "year_of_passing": 2001, "previous_employer": "Ernst & Young", "experience_years": 23,
        "domain": "Internal Audit", "skills": "Risk Assessment, Internal Controls, Compliance, IND AS",
        "certifications": "CA, CIA",
        "emergency_contact_name": "Revathi Aiyer", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345110",
        "blood_group": "A-", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "chandrasekar.a@gmail.com", "personal_phone": "+91-9012345010",
        "current_address": "H.No 3-78, Asilmetta, Visakhapatnam 530003",
        "permanent_address": "H.No 3-78, Asilmetta, Visakhapatnam 530003",
        "password": "123456",
    },
    # ── Sales Manager (1) ─────────────────────────────────────────────────
    {
        "employee_code": "IPG-011",
        "first_name": "Venkata Ramana", "last_name": "Iyengar",
        "work_email": "venkataramana.iyengar@impacgo.com",
        "role_name": "Sales Manager",
        "phone": "+91-8912345011", "gender": "Male",
        "date_of_birth": datetime.date(1981, 1, 28),
        "date_of_joining": datetime.date(2016, 1, 3),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "SLS",
        "sub_department": "Domestic Sales",
        "designation_name": "Manager",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 4,
        "annual_ctc": 1500000,
        "reporting_manager_code": "IPG-001",
        "pan": "KKKVI1234K",
        "bank_name": "Axis Bank", "bank_account_no": "91512345011", "bank_ifsc": "UTIB0002345",
        "qualification": "MBA Marketing", "institute": "Symbiosis Pune", "specialization": "Marketing",
        "year_of_passing": 2004, "previous_employer": "Larsen & Toubro", "experience_years": 20,
        "domain": "B2B Sales", "skills": "Sales Strategy, Key Account Management, ERP Modules, CRM",
        "certifications": "Certified Sales Professional",
        "emergency_contact_name": "Vasantha Iyengar", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345111",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "venkataramana.i@gmail.com", "personal_phone": "+91-9012345011",
        "current_address": "Flat 701, Gachibowli, Hyderabad 500032",
        "permanent_address": "12-5, Waltair Main Road, Visakhapatnam 530002",
        "password": "123456",
    },
    # ── Sales Executives (5) ──────────────────────────────────────────────
    {
        "employee_code": "IPG-012",
        "first_name": "Suresh Babu", "last_name": "Kotha",
        "work_email": "sureshbabu.kotha@impacgo.com",
        "role_name": "Sales Executive",
        "phone": "+91-8912345012", "gender": "Male",
        "date_of_birth": datetime.date(1993, 10, 5),
        "date_of_joining": datetime.date(2019, 6, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "SLS",
        "sub_department": "Domestic Sales",
        "designation_name": "Senior Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 750000,
        "reporting_manager_code": "IPG-011",
        "pan": "LLLSK2345L",
        "bank_name": "SBI", "bank_account_no": "30012345012", "bank_ifsc": "SBIN0004567",
        "qualification": "B.E. Mechanical", "institute": "JNTU Kakinada", "specialization": "Mechanical Engineering",
        "year_of_passing": 2015, "previous_employer": "Bharat Forge", "experience_years": 9,
        "domain": "Industrial Sales", "skills": "Sales, Negotiation, SAP SD, CRM",
        "certifications": "",
        "emergency_contact_name": "Ramaiah Kotha", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345112",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "sureshbabu.k@gmail.com", "personal_phone": "+91-9012345012",
        "current_address": "Flat 204, Kondapur, Hyderabad 500084",
        "permanent_address": "6-7, Narasapur, West Godavari 534275",
        "password": "123456",
    },
    {
        "employee_code": "IPG-013",
        "first_name": "Ramya", "last_name": "Krishnamurthy",
        "work_email": "ramya.krishnamurthy@impacgo.com",
        "role_name": "Sales Executive",
        "phone": "+91-8912345013", "gender": "Female",
        "date_of_birth": datetime.date(1995, 4, 12),
        "date_of_joining": datetime.date(2020, 2, 3),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "SLS",
        "sub_department": "Digital Marketing",
        "designation_name": "Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 6,
        "annual_ctc": 620000,
        "reporting_manager_code": "IPG-011",
        "pan": "MMMRK3456M",
        "bank_name": "ICICI Bank", "bank_account_no": "02612345013", "bank_ifsc": "ICIC0003456",
        "qualification": "BBA", "institute": "Osmania University", "specialization": "Marketing",
        "year_of_passing": 2017, "previous_employer": "Tata Motors", "experience_years": 7,
        "domain": "Digital & Retail Sales", "skills": "Digital Marketing, Sales Analytics, Salesforce",
        "certifications": "Google Analytics",
        "emergency_contact_name": "Krishnamurthy R", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345113",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "ramya.k@gmail.com", "personal_phone": "+91-9012345013",
        "current_address": "Flat 103, KPHB Colony, Hyderabad 500072",
        "permanent_address": "45-6, R.T. Nagar, Bengaluru 560032",
        "password": "123456",
    },
    {
        "employee_code": "IPG-014",
        "first_name": "Kiran", "last_name": "Shankar",
        "work_email": "kiran.shankar@impacgo.com",
        "role_name": "Sales Executive",
        "phone": "+91-8912345014", "gender": "Male",
        "date_of_birth": datetime.date(1991, 12, 22),
        "date_of_joining": datetime.date(2018, 8, 20),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "SLS",
        "sub_department": "Export Sales",
        "designation_name": "Senior Executive",
        "team": "Sales", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 700000,
        "reporting_manager_code": "IPG-011",
        "pan": "NNNKS4567N",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345014", "bank_ifsc": "HDFC0004567",
        "qualification": "B.Com", "institute": "Andhra University", "specialization": "Commerce",
        "year_of_passing": 2013, "previous_employer": "SAIL", "experience_years": 11,
        "domain": "Export Sales", "skills": "Export Documentation, EXIM, Trade Finance, SAP",
        "certifications": "IIFT Export Management",
        "emergency_contact_name": "Shankar Rao", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345114",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "kiran.shankar@gmail.com", "personal_phone": "+91-9012345014",
        "current_address": "H.No 5-22, Gajuwaka, Visakhapatnam 530026",
        "permanent_address": "H.No 5-22, Gajuwaka, Visakhapatnam 530026",
        "password": "123456",
    },
    {
        "employee_code": "IPG-015",
        "first_name": "Pooja", "last_name": "Acharya",
        "work_email": "pooja.acharya@impacgo.com",
        "role_name": "Sales Executive",
        "phone": "+91-8912345015", "gender": "Female",
        "date_of_birth": datetime.date(1997, 7, 3),
        "date_of_joining": datetime.date(2021, 6, 7),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "SLS",
        "sub_department": "Domestic Sales",
        "designation_name": "Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 6,
        "annual_ctc": 580000,
        "reporting_manager_code": "IPG-011",
        "pan": "OOOAP5678O",
        "bank_name": "Kotak Bank", "bank_account_no": "63012345015", "bank_ifsc": "KKBK0001234",
        "qualification": "MBA", "institute": "ICFAI Hyderabad", "specialization": "Sales & Marketing",
        "year_of_passing": 2020, "previous_employer": None, "experience_years": 3,
        "domain": "Inside Sales", "skills": "Inside Sales, Lead Generation, HubSpot, MS Office",
        "certifications": "",
        "emergency_contact_name": "Arun Acharya", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345115",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "pooja.acharya@gmail.com", "personal_phone": "+91-9012345015",
        "current_address": "Flat 505, Hitech City, Hyderabad 500081",
        "permanent_address": "23-4, Mangalore 575001",
        "password": "123456",
    },
    {
        "employee_code": "IPG-016",
        "first_name": "Bharath", "last_name": "Chandra",
        "work_email": "bharath.chandra@impacgo.com",
        "role_name": "Sales Executive",
        "phone": "+91-8912345016", "gender": "Male",
        "date_of_birth": datetime.date(1989, 3, 17),
        "date_of_joining": datetime.date(2017, 5, 15),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "SLS",
        "sub_department": "Domestic Sales",
        "designation_name": "Senior Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 780000,
        "reporting_manager_code": "IPG-011",
        "pan": "PPPBC6789P",
        "bank_name": "SBI", "bank_account_no": "30012345016", "bank_ifsc": "SBIN0005678",
        "qualification": "B.Tech", "institute": "JNTU Hyderabad", "specialization": "Electrical Engineering",
        "year_of_passing": 2011, "previous_employer": "Schneider Electric", "experience_years": 13,
        "domain": "Electrical & Industrial Sales", "skills": "Technical Sales, Product Demo, SAP CRM",
        "certifications": "",
        "emergency_contact_name": "Suma Chandra", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345116",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "bharath.c@gmail.com", "personal_phone": "+91-9012345016",
        "current_address": "H.No 2-34, Banjara Hills, Hyderabad 500034",
        "permanent_address": "H.No 2-34, Banjara Hills, Hyderabad 500034",
        "password": "123456",
    },
    # ── Procurement Manager (1) ───────────────────────────────────────────
    {
        "employee_code": "IPG-017",
        "first_name": "Arun Kumar", "last_name": "Patel",
        "work_email": "arunkumar.patel@impacgo.com",
        "role_name": "Procurement Manager",
        "phone": "+91-8912345017", "gender": "Male",
        "date_of_birth": datetime.date(1980, 9, 8),
        "date_of_joining": datetime.date(2015, 11, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "PCR",
        "sub_department": "Vendor Management",
        "designation_name": "Manager",
        "team": "Procurement", "work_mode": "On-site", "numeric_band": 4,
        "annual_ctc": 1300000,
        "reporting_manager_code": "IPG-001",
        "pan": "QQQAP7890Q",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345017", "bank_ifsc": "HDFC0005678",
        "qualification": "B.E. Mechanical", "institute": "NIT Warangal", "specialization": "Mechanical Engineering",
        "year_of_passing": 2002, "previous_employer": "NMDC", "experience_years": 22,
        "domain": "Strategic Procurement", "skills": "Vendor Negotiation, SAP MM, Supply Chain, Contract Management",
        "certifications": "CPSM",
        "emergency_contact_name": "Kalpana Patel", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345117",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "arunkumar.p@gmail.com", "personal_phone": "+91-9012345017",
        "current_address": "H.No 6-43, Srinagar, Visakhapatnam 530044",
        "permanent_address": "H.No 6-43, Srinagar, Visakhapatnam 530044",
        "password": "123456",
    },
    # ── Buyers (2) ────────────────────────────────────────────────────────
    {
        "employee_code": "IPG-018",
        "first_name": "Sindhu", "last_name": "Varma",
        "work_email": "sindhu.varma@impacgo.com",
        "role_name": "Buyer",
        "phone": "+91-8912345018", "gender": "Female",
        "date_of_birth": datetime.date(1993, 5, 14),
        "date_of_joining": datetime.date(2019, 9, 2),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "PCR",
        "sub_department": "Purchase Operations",
        "designation_name": "Senior Executive",
        "team": "Procurement", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 680000,
        "reporting_manager_code": "IPG-017",
        "pan": "RRRSV8901R",
        "bank_name": "Axis Bank", "bank_account_no": "91512345018", "bank_ifsc": "UTIB0003456",
        "qualification": "B.E. Mechanical", "institute": "JNTU Kakinada", "specialization": "Mechanical",
        "year_of_passing": 2015, "previous_employer": "RINL Vizag Steel", "experience_years": 9,
        "domain": "Raw Material Procurement", "skills": "Vendor Evaluation, SAP MM, Purchase Order, BOM",
        "certifications": "",
        "emergency_contact_name": "Ramesh Varma", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345118",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "sindhu.varma@gmail.com", "personal_phone": "+91-9012345018",
        "current_address": "H.No 9-12, Steel Plant Colony, Visakhapatnam 530031",
        "permanent_address": "H.No 9-12, Steel Plant Colony, Visakhapatnam 530031",
        "password": "123456",
    },
    {
        "employee_code": "IPG-019",
        "first_name": "Mahesh Babu", "last_name": "Naidu",
        "work_email": "maheshbabu.naidu@impacgo.com",
        "role_name": "Buyer",
        "phone": "+91-8912345019", "gender": "Male",
        "date_of_birth": datetime.date(1991, 11, 30),
        "date_of_joining": datetime.date(2020, 1, 6),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "PCR",
        "sub_department": "Vendor Management",
        "designation_name": "Executive",
        "team": "Procurement", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 590000,
        "reporting_manager_code": "IPG-017",
        "pan": "SSSBN9012S",
        "bank_name": "SBI", "bank_account_no": "30012345019", "bank_ifsc": "SBIN0006789",
        "qualification": "B.Com", "institute": "Andhra University", "specialization": "Commerce",
        "year_of_passing": 2013, "previous_employer": "Hindustan Zinc", "experience_years": 11,
        "domain": "Indirect Procurement", "skills": "E-Procurement, Vendor Development, SAP",
        "certifications": "",
        "emergency_contact_name": "Latha Naidu", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-8912345119",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "maheshbabu.n@gmail.com", "personal_phone": "+91-9012345019",
        "current_address": "H.No 14-6, Bheemunipatnam, Vizag 531163",
        "permanent_address": "H.No 14-6, Bheemunipatnam, Vizag 531163",
        "password": "123456",
    },
    # ── Warehouse Manager (1) ─────────────────────────────────────────────
    {
        "employee_code": "IPG-020",
        "first_name": "Gopala Krishna", "last_name": "Shetty",
        "work_email": "gopalakrishna.shetty@impacgo.com",
        "role_name": "Warehouse Manager",
        "phone": "+91-8912345020", "gender": "Male",
        "date_of_birth": datetime.date(1978, 2, 14),
        "date_of_joining": datetime.date(2014, 7, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "WHS",
        "sub_department": "Inventory Control",
        "designation_name": "Manager",
        "team": "Operations", "work_mode": "On-site", "numeric_band": 4,
        "annual_ctc": 1100000,
        "reporting_manager_code": "IPG-001",
        "pan": "TTTGK0123T",
        "bank_name": "Canara Bank", "bank_account_no": "12312345020", "bank_ifsc": "CNRB0002345",
        "qualification": "B.E. Industrial Engineering", "institute": "NIT Surathkal", "specialization": "Industrial Engg",
        "year_of_passing": 2000, "previous_employer": "Mahindra Logistics", "experience_years": 24,
        "domain": "Warehouse Operations", "skills": "WMS, SAP WM, Inventory Management, 5S, Lean",
        "certifications": "APICS CPIM",
        "emergency_contact_name": "Vijaya Shetty", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345120",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "gopalakrishna.s@gmail.com", "personal_phone": "+91-9012345020",
        "current_address": "H.No 2-11, Bhavani Nagar, Visakhapatnam 530024",
        "permanent_address": "H.No 2-11, Bhavani Nagar, Visakhapatnam 530024",
        "password": "123456",
    },
    # ── Store Keepers (2) ─────────────────────────────────────────────────
    {
        "employee_code": "IPG-021",
        "first_name": "Balaji", "last_name": "Venkatesh",
        "work_email": "balaji.venkatesh@impacgo.com",
        "role_name": "Store Keeper",
        "phone": "+91-8912345021", "gender": "Male",
        "date_of_birth": datetime.date(1990, 6, 9),
        "date_of_joining": datetime.date(2018, 3, 5),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "WHS",
        "sub_department": "Inbound",
        "designation_name": "Senior Executive",
        "team": "Operations", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 550000,
        "reporting_manager_code": "IPG-020",
        "pan": "UUUBV1234U",
        "bank_name": "SBI", "bank_account_no": "30012345021", "bank_ifsc": "SBIN0007890",
        "qualification": "B.Sc", "institute": "Andhra University", "specialization": "Physics",
        "year_of_passing": 2012, "previous_employer": "TVS Supply Chain", "experience_years": 12,
        "domain": "Store Operations", "skills": "Inventory Control, GRN, SAP MM, Barcode Scanning",
        "certifications": "",
        "emergency_contact_name": "Kamala Venkatesh", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-8912345121",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "balaji.v@gmail.com", "personal_phone": "+91-9012345021",
        "current_address": "H.No 11-34, Kommadi, Vizag 530048",
        "permanent_address": "H.No 11-34, Kommadi, Vizag 530048",
        "password": "123456",
    },
    {
        "employee_code": "IPG-022",
        "first_name": "Sowmya", "last_name": "Devi",
        "work_email": "sowmya.devi@impacgo.com",
        "role_name": "Store Keeper",
        "phone": "+91-8912345022", "gender": "Female",
        "date_of_birth": datetime.date(1994, 8, 25),
        "date_of_joining": datetime.date(2020, 5, 11),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "WHS",
        "sub_department": "Outbound",
        "designation_name": "Executive",
        "team": "Operations", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 480000,
        "reporting_manager_code": "IPG-020",
        "pan": "VVVSD2345V",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345022", "bank_ifsc": "HDFC0006789",
        "qualification": "B.Com", "institute": "Andhra University", "specialization": "Commerce",
        "year_of_passing": 2016, "previous_employer": "Amazon India", "experience_years": 6,
        "domain": "Warehouse Operations", "skills": "Dispatch, Packing, SAP WM, Stock Reconciliation",
        "certifications": "",
        "emergency_contact_name": "Rao Devi", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345122",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "sowmya.devi@gmail.com", "personal_phone": "+91-9012345022",
        "current_address": "H.No 4-88, Maddilapalem, Visakhapatnam 530013",
        "permanent_address": "H.No 4-88, Maddilapalem, Visakhapatnam 530013",
        "password": "123456",
    },
    # ── Production Manager (1) ────────────────────────────────────────────
    {
        "employee_code": "IPG-023",
        "first_name": "Narayana Murthy", "last_name": "Bhat",
        "work_email": "narayanamurthy.bhat@impacgo.com",
        "role_name": "Production Manager",
        "phone": "+91-8912345023", "gender": "Male",
        "date_of_birth": datetime.date(1976, 11, 3),
        "date_of_joining": datetime.date(2013, 9, 15),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "MFG",
        "sub_department": "Production Line A",
        "designation_name": "Senior Manager",
        "team": "Production", "work_mode": "On-site", "numeric_band": 4,
        "annual_ctc": 1700000,
        "reporting_manager_code": "IPG-001",
        "pan": "WWWNB3456W",
        "bank_name": "ICICI Bank", "bank_account_no": "02612345023", "bank_ifsc": "ICIC0004567",
        "qualification": "B.E. Mechanical", "institute": "BITS Pilani", "specialization": "Mechanical Engineering",
        "year_of_passing": 1998, "previous_employer": "Tata Steel", "experience_years": 26,
        "domain": "Manufacturing & Production", "skills": "Production Planning, SAP PP, Lean Manufacturing, Six Sigma",
        "certifications": "Six Sigma Black Belt",
        "emergency_contact_name": "Usha Bhat", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345123",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "narayanamurthy.b@gmail.com", "personal_phone": "+91-9012345023",
        "current_address": "H.No 1-56, Bheemunipatnam Road, Visakhapatnam 530048",
        "permanent_address": "H.No 1-56, Bheemunipatnam Road, Visakhapatnam 530048",
        "password": "123456",
    },
    # ── Shop Floor Operators (5) ──────────────────────────────────────────
    {
        "employee_code": "IPG-024",
        "first_name": "Srinivasa", "last_name": "Venkataramaiah",
        "work_email": "srinivasa.v@impacgo.com",
        "role_name": "Shop Floor Operator",
        "phone": "+91-8912345024", "gender": "Male",
        "date_of_birth": datetime.date(1988, 4, 7),
        "date_of_joining": datetime.date(2016, 3, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "MFG",
        "sub_department": "Production Line A",
        "designation_name": "Senior Operator",
        "team": "Production", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 380000,
        "reporting_manager_code": "IPG-023",
        "pan": "XXXSV4567X",
        "bank_name": "SBI", "bank_account_no": "30012345024", "bank_ifsc": "SBIN0008901",
        "qualification": "ITI", "institute": "Govt ITI Visakhapatnam", "specialization": "Fitter",
        "year_of_passing": 2008, "previous_employer": "HPCL Visakhapatnam", "experience_years": 16,
        "domain": "CNC Machining", "skills": "CNC Operation, Machine Maintenance, Quality Check",
        "certifications": "",
        "emergency_contact_name": "Sarada Venkataramaiah", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345124",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "srinivasa.v@gmail.com", "personal_phone": "+91-9012345024",
        "current_address": "H.No 8-23, Gajuwaka, Visakhapatnam 530026",
        "permanent_address": "H.No 8-23, Gajuwaka, Visakhapatnam 530026",
        "password": "123456",
    },
    {
        "employee_code": "IPG-025",
        "first_name": "Hanumantha", "last_name": "Goud",
        "work_email": "hanumantha.goud@impacgo.com",
        "role_name": "Shop Floor Operator",
        "phone": "+91-8912345025", "gender": "Male",
        "date_of_birth": datetime.date(1992, 2, 19),
        "date_of_joining": datetime.date(2018, 6, 4),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "MFG",
        "sub_department": "Production Line B",
        "designation_name": "Operator",
        "team": "Production", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 340000,
        "reporting_manager_code": "IPG-023",
        "pan": "YYYHG5678Y",
        "bank_name": "Canara Bank", "bank_account_no": "12312345025", "bank_ifsc": "CNRB0003456",
        "qualification": "ITI", "institute": "Govt ITI Vizag", "specialization": "Welder",
        "year_of_passing": 2011, "previous_employer": "Hindustan Shipyard", "experience_years": 11,
        "domain": "Welding & Fabrication", "skills": "Arc Welding, MIG/TIG, Safety Standards",
        "certifications": "",
        "emergency_contact_name": "Radha Goud", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345125",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "hanumantha.g@gmail.com", "personal_phone": "+91-9012345025",
        "current_address": "H.No 3-45, Malkapuram, Visakhapatnam 530011",
        "permanent_address": "H.No 3-45, Malkapuram, Visakhapatnam 530011",
        "password": "123456",
    },
    {
        "employee_code": "IPG-026",
        "first_name": "Ranga Rao", "last_name": "Jagannadh",
        "work_email": "rangarao.jagannadh@impacgo.com",
        "role_name": "Shop Floor Operator",
        "phone": "+91-8912345026", "gender": "Male",
        "date_of_birth": datetime.date(1990, 8, 11),
        "date_of_joining": datetime.date(2017, 4, 10),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "MFG",
        "sub_department": "Assembly",
        "designation_name": "Senior Operator",
        "team": "Production", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 360000,
        "reporting_manager_code": "IPG-023",
        "pan": "ZZZRJ6789Z",
        "bank_name": "SBI", "bank_account_no": "30012345026", "bank_ifsc": "SBIN0009012",
        "qualification": "Diploma Mechanical", "institute": "Govt Polytechnic Vizag", "specialization": "Mechanical",
        "year_of_passing": 2010, "previous_employer": "Coromandel International", "experience_years": 14,
        "domain": "Assembly Operations", "skills": "Assembly, Torque Tools, Quality Inspection, 5S",
        "certifications": "",
        "emergency_contact_name": "Jhansi Jagannadh", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345126",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "rangarao.j@gmail.com", "personal_phone": "+91-9012345026",
        "current_address": "H.No 6-78, Dondaparthy, Visakhapatnam 530016",
        "permanent_address": "H.No 6-78, Dondaparthy, Visakhapatnam 530016",
        "password": "123456",
    },
    {
        "employee_code": "IPG-027",
        "first_name": "Satya Narayana", "last_name": "Murti",
        "work_email": "satyanarayana.murti@impacgo.com",
        "role_name": "Shop Floor Operator",
        "phone": "+91-8912345027", "gender": "Male",
        "date_of_birth": datetime.date(1987, 12, 28),
        "date_of_joining": datetime.date(2015, 10, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "MFG",
        "sub_department": "Production Line A",
        "designation_name": "Senior Operator",
        "team": "Production", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 370000,
        "reporting_manager_code": "IPG-023",
        "pan": "AAABM7890A",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345027", "bank_ifsc": "HDFC0007890",
        "qualification": "ITI", "institute": "Govt ITI Anakapalle", "specialization": "Turner",
        "year_of_passing": 2007, "previous_employer": "Vizag Steel", "experience_years": 17,
        "domain": "Turning & Milling", "skills": "Lathe Operation, CNC Turning, Precision Measurement",
        "certifications": "",
        "emergency_contact_name": "Sarojini Murti", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345127",
        "blood_group": "B-", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "satyanarayana.m@gmail.com", "personal_phone": "+91-9012345027",
        "current_address": "H.No 5-67, Anakapalle, Vizag 531001",
        "permanent_address": "H.No 5-67, Anakapalle, Vizag 531001",
        "password": "123456",
    },
    {
        "employee_code": "IPG-028",
        "first_name": "Praveen Kumar", "last_name": "Yadav",
        "work_email": "praveenkumar.yadav@impacgo.com",
        "role_name": "Shop Floor Operator",
        "phone": "+91-8912345028", "gender": "Male",
        "date_of_birth": datetime.date(1995, 3, 22),
        "date_of_joining": datetime.date(2021, 8, 2),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "MFG",
        "sub_department": "Production Line B",
        "designation_name": "Operator",
        "team": "Production", "work_mode": "On-site", "numeric_band": 7,
        "annual_ctc": 310000,
        "reporting_manager_code": "IPG-023",
        "pan": "BBBPY8901B",
        "bank_name": "SBI", "bank_account_no": "30012345028", "bank_ifsc": "SBIN0010123",
        "qualification": "ITI", "institute": "Govt ITI Bheemunipatnam", "specialization": "Electrician",
        "year_of_passing": 2015, "previous_employer": None, "experience_years": 3,
        "domain": "Electrical Assembly", "skills": "Electrical Wiring, Panel Assembly, Multimeter",
        "certifications": "",
        "emergency_contact_name": "Ramesh Yadav", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345128",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "praveenkumar.y@gmail.com", "personal_phone": "+91-9012345028",
        "current_address": "H.No 7-34, Bheemunipatnam, Vizag 531163",
        "permanent_address": "H.No 7-34, Bheemunipatnam, Vizag 531163",
        "password": "123456",
    },
    # ── Quality Inspectors (2) ────────────────────────────────────────────
    {
        "employee_code": "IPG-029",
        "first_name": "Venkateswara", "last_name": "Kondapalli",
        "work_email": "venkateswara.k@impacgo.com",
        "role_name": "Quality Inspector",
        "phone": "+91-8912345029", "gender": "Male",
        "date_of_birth": datetime.date(1986, 7, 16),
        "date_of_joining": datetime.date(2016, 5, 2),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "QC",
        "sub_department": "In-Process QC",
        "designation_name": "Senior Executive",
        "team": "Quality", "work_mode": "On-site", "numeric_band": 5,
        "annual_ctc": 620000,
        "reporting_manager_code": "IPG-023",
        "pan": "CCCVK9012C",
        "bank_name": "ICICI Bank", "bank_account_no": "02612345029", "bank_ifsc": "ICIC0005678",
        "qualification": "B.E. Mechanical", "institute": "JNTU Kakinada", "specialization": "Mechanical",
        "year_of_passing": 2008, "previous_employer": "BEML Ltd", "experience_years": 16,
        "domain": "Quality Assurance", "skills": "ISO 9001, SPC, CMM, Non-Destructive Testing, SAP QM",
        "certifications": "Lead Auditor ISO 9001",
        "emergency_contact_name": "Nirmala Kondapalli", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345129",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "venkateswara.k@gmail.com", "personal_phone": "+91-9012345029",
        "current_address": "H.No 2-89, Kommadi Junction, Vizag 530048",
        "permanent_address": "H.No 2-89, Kommadi Junction, Vizag 530048",
        "password": "123456",
    },
    {
        "employee_code": "IPG-030",
        "first_name": "Naga Lakshmi", "last_name": "Pillai",
        "work_email": "nagalakshmi.pillai@impacgo.com",
        "role_name": "Quality Inspector",
        "phone": "+91-8912345030", "gender": "Female",
        "date_of_birth": datetime.date(1991, 1, 10),
        "date_of_joining": datetime.date(2019, 11, 4),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "QC",
        "sub_department": "Final Inspection",
        "designation_name": "Executive",
        "team": "Quality", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 520000,
        "reporting_manager_code": "IPG-023",
        "pan": "DDDNP0123D",
        "bank_name": "Axis Bank", "bank_account_no": "91512345030", "bank_ifsc": "UTIB0004567",
        "qualification": "B.Sc Chemistry", "institute": "Andhra University", "specialization": "Chemistry",
        "year_of_passing": 2013, "previous_employer": "Dr Reddys Labs", "experience_years": 11,
        "domain": "Product Quality", "skills": "Incoming Inspection, Sampling Plans, AQL, Metrology",
        "certifications": "",
        "emergency_contact_name": "Krishnan Pillai", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345130",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "nagalakshmi.p@gmail.com", "personal_phone": "+91-9012345030",
        "current_address": "Flat 102, Rushikonda, Visakhapatnam 530045",
        "permanent_address": "TC-5-678, Trivandrum 695025",
        "password": "123456",
    },
    # ── CRM Executive (2) ─────────────────────────────────────────────────
    {
        "employee_code": "IPG-031",
        "first_name": "Shobha Rani", "last_name": "Nambiar",
        "work_email": "shobharani.nambiar@impacgo.com",
        "role_name": "CRM Executive",
        "phone": "+91-8912345031", "gender": "Female",
        "date_of_birth": datetime.date(1987, 9, 25),
        "date_of_joining": datetime.date(2017, 1, 16),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "CRM",
        "sub_department": "Account Management",
        "designation_name": "Senior Executive",
        "team": "CRM", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 750000,
        "reporting_manager_code": "IPG-011",
        "pan": "EEESN1234E",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345031", "bank_ifsc": "HDFC0008901",
        "qualification": "MBA Marketing", "institute": "Symbiosis Pune", "specialization": "Marketing & CRM",
        "year_of_passing": 2010, "previous_employer": "Oracle India", "experience_years": 14,
        "domain": "CRM & Key Accounts", "skills": "Salesforce, CRM, Key Account Management, Customer Retention",
        "certifications": "Salesforce Administrator",
        "emergency_contact_name": "Rajan Nambiar", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345131",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "shobharani.n@gmail.com", "personal_phone": "+91-9012345031",
        "current_address": "Flat 304, Jubilee Hills, Hyderabad 500033",
        "permanent_address": "12-56, Calicut 673001",
        "password": "123456",
    },
    {
        "employee_code": "IPG-032",
        "first_name": "Anand Rao", "last_name": "Kapoor",
        "work_email": "anandrao.kapoor@impacgo.com",
        "role_name": "CRM Executive",
        "phone": "+91-8912345032", "gender": "Male",
        "date_of_birth": datetime.date(1990, 5, 19),
        "date_of_joining": datetime.date(2018, 9, 3),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "CRM",
        "sub_department": "Customer Support",
        "designation_name": "Senior Executive",
        "team": "CRM", "work_mode": "Hybrid", "numeric_band": 5,
        "annual_ctc": 700000,
        "reporting_manager_code": "IPG-011",
        "pan": "FFFAK2345F",
        "bank_name": "ICICI Bank", "bank_account_no": "02612345032", "bank_ifsc": "ICIC0006789",
        "qualification": "B.Tech", "institute": "JNTU Hyderabad", "specialization": "CSE",
        "year_of_passing": 2012, "previous_employer": "SAP India", "experience_years": 12,
        "domain": "Technical CRM", "skills": "SAP CRM, Ticketing, Escalation Management, Customer Analytics",
        "certifications": "SAP CRM Consultant",
        "emergency_contact_name": "Priya Kapoor", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345132",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "anandrao.k@gmail.com", "personal_phone": "+91-9012345032",
        "current_address": "Flat 601, Madhapur, Hyderabad 500081",
        "permanent_address": "H.No 4-56, Rohini Sector 6, Delhi 110085",
        "password": "123456",
    },
    # ── Support Agents (3) ────────────────────────────────────────────────
    {
        "employee_code": "IPG-033",
        "first_name": "Harish Chandra", "last_name": "Gupta",
        "work_email": "harishchandra.gupta@impacgo.com",
        "role_name": "Support Agent",
        "phone": "+91-8912345033", "gender": "Male",
        "date_of_birth": datetime.date(1996, 11, 4),
        "date_of_joining": datetime.date(2021, 3, 8),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "CRM",
        "sub_department": "Customer Support",
        "designation_name": "Executive",
        "team": "CRM", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 430000,
        "reporting_manager_code": "IPG-031",
        "pan": "GGGNG3456G",
        "bank_name": "SBI", "bank_account_no": "30012345033", "bank_ifsc": "SBIN0011234",
        "qualification": "B.A.", "institute": "Osmania University", "specialization": "English",
        "year_of_passing": 2018, "previous_employer": "Concentrix", "experience_years": 5,
        "domain": "Customer Support", "skills": "Ticket Resolution, CRM Tools, Communication, SLA Management",
        "certifications": "",
        "emergency_contact_name": "Suresh Gupta", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345133",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "harishchandra.g@gmail.com", "personal_phone": "+91-9012345033",
        "current_address": "Flat 205, Ameerpet, Hyderabad 500016",
        "permanent_address": "H.No 2-45, Kanpur 208001",
        "password": "123456",
    },
    {
        "employee_code": "IPG-034",
        "first_name": "Preethi", "last_name": "Krishnan",
        "work_email": "preethi.krishnan@impacgo.com",
        "role_name": "Support Agent",
        "phone": "+91-8912345034", "gender": "Female",
        "date_of_birth": datetime.date(1998, 6, 29),
        "date_of_joining": datetime.date(2022, 1, 17),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "CRM",
        "sub_department": "Customer Support",
        "designation_name": "Executive",
        "team": "CRM", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 400000,
        "reporting_manager_code": "IPG-031",
        "pan": "HHHPK4567H",
        "bank_name": "Axis Bank", "bank_account_no": "91512345034", "bank_ifsc": "UTIB0005678",
        "qualification": "B.Com", "institute": "Osmania University", "specialization": "Commerce",
        "year_of_passing": 2020, "previous_employer": None, "experience_years": 2,
        "domain": "Customer Support", "skills": "Call Handling, Zendesk, Email Support, Data Entry",
        "certifications": "",
        "emergency_contact_name": "Krishnan T", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345134",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "preethi.k@gmail.com", "personal_phone": "+91-9012345034",
        "current_address": "Flat 102, Moti Nagar, Hyderabad 500018",
        "permanent_address": "TC-8-9, Trivandrum 695003",
        "password": "123456",
    },
    {
        "employee_code": "IPG-035",
        "first_name": "Rohit", "last_name": "Tiwari",
        "work_email": "rohit.tiwari@impacgo.com",
        "role_name": "Support Agent",
        "phone": "+91-8912345035", "gender": "Male",
        "date_of_birth": datetime.date(1997, 2, 13),
        "date_of_joining": datetime.date(2021, 11, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "CRM",
        "sub_department": "Customer Support",
        "designation_name": "Executive",
        "team": "CRM", "work_mode": "On-site", "numeric_band": 6,
        "annual_ctc": 420000,
        "reporting_manager_code": "IPG-032",
        "pan": "IIIRT5678I",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345035", "bank_ifsc": "HDFC0009012",
        "qualification": "BCA", "institute": "Hyderabad University", "specialization": "Computer Applications",
        "year_of_passing": 2019, "previous_employer": "Infosys BPM", "experience_years": 4,
        "domain": "Technical Support", "skills": "L1/L2 Support, ITSM, Remote Troubleshooting, JIRA",
        "certifications": "ITIL Foundation",
        "emergency_contact_name": "Ramesh Tiwari", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345135",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "rohit.tiwari@gmail.com", "personal_phone": "+91-9012345035",
        "current_address": "H.No 5-23, Ameerpet, Hyderabad 500016",
        "permanent_address": "H.No 5-23, Lucknow 226001",
        "password": "123456",
    },
    # ── Approver (1) ──────────────────────────────────────────────────────
    {
        "employee_code": "IPG-036",
        "first_name": "Lakshmi Narayana", "last_name": "Rao",
        "work_email": "lakshminarayana.rao@impacgo.com",
        "role_name": "Approver",
        "phone": "+91-8912345036", "gender": "Male",
        "date_of_birth": datetime.date(1975, 8, 30),
        "date_of_joining": datetime.date(2012, 4, 2),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "EXO",
        "sub_department": "Corporate Affairs",
        "designation_name": "General Manager",
        "team": "Leadership", "work_mode": "On-site", "numeric_band": 3,
        "annual_ctc": 2200000,
        "reporting_manager_code": "IPG-001",
        "pan": "JJJLR6789J",
        "bank_name": "HDFC Bank", "bank_account_no": "50012345036", "bank_ifsc": "HDFC0010123",
        "qualification": "MBA Finance", "institute": "IIM Bangalore", "specialization": "Finance",
        "year_of_passing": 1999, "previous_employer": "Bharat Petroleum", "experience_years": 25,
        "domain": "Operations & Compliance", "skills": "Operations Management, Compliance, Approvals, Board Reporting",
        "certifications": "CFA",
        "emergency_contact_name": "Kamala Rao", "emergency_contact_relation": "Spouse", "emergency_contact_phone": "+91-8912345136",
        "blood_group": "AB+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "lakshminarayana.r@gmail.com", "personal_phone": "+91-9012345036",
        "current_address": "H.No 1-100, Rushikonda Hills, Visakhapatnam 530045",
        "permanent_address": "H.No 1-100, Rushikonda Hills, Visakhapatnam 530045",
        "password": "123456",
    },
    # ── Employee (ESS) – general employees ────────────────────────────────
    {
        "employee_code": "IPG-037",
        "first_name": "Vijaya Lakshmi", "last_name": "Reddy",
        "work_email": "vijayalakshmi.reddy@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345037", "gender": "Female",
        "date_of_birth": datetime.date(1993, 4, 16),
        "date_of_joining": datetime.date(2020, 7, 1),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "HR",
        "sub_department": "HR Operations", "designation_name": "Executive",
        "team": "HR", "work_mode": "On-site", "numeric_band": 6, "annual_ctc": 480000,
        "reporting_manager_code": "IPG-003",
        "pan": "KKKXR7890K", "bank_name": "SBI", "bank_account_no": "30012345037", "bank_ifsc": "SBIN0012345",
        "qualification": "BBA", "institute": "Andhra University", "specialization": "HR",
        "year_of_passing": 2015, "previous_employer": None, "experience_years": 4,
        "domain": "HR", "skills": "Employee Records, Onboarding, Attendance Management",
        "certifications": "",
        "emergency_contact_name": "Ramaiah Reddy", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345137",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "vijayalakshmi.r@gmail.com", "personal_phone": "+91-9012345037",
        "current_address": "H.No 4-12, Ram Nagar, Visakhapatnam 530002",
        "permanent_address": "H.No 4-12, Ram Nagar, Visakhapatnam 530002",
        "password": "123456",
    },
    {
        "employee_code": "IPG-038",
        "first_name": "Murali Krishna", "last_name": "Varma",
        "work_email": "murali.varma@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345038", "gender": "Male",
        "date_of_birth": datetime.date(1995, 10, 21),
        "date_of_joining": datetime.date(2021, 4, 5),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "SLS",
        "sub_department": "Digital Marketing", "designation_name": "Executive",
        "team": "Sales", "work_mode": "Hybrid", "numeric_band": 6, "annual_ctc": 500000,
        "reporting_manager_code": "IPG-011",
        "pan": "LLLMV8901L", "bank_name": "Axis Bank", "bank_account_no": "91512345038", "bank_ifsc": "UTIB0006789",
        "qualification": "B.Tech", "institute": "JNTU Hyderabad", "specialization": "CSE",
        "year_of_passing": 2017, "previous_employer": "Persistent Systems", "experience_years": 6,
        "domain": "Sales Operations", "skills": "CRM Data Entry, Lead Tracking, Reporting",
        "certifications": "",
        "emergency_contact_name": "Krishna Varma", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345138",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "murali.varma@gmail.com", "personal_phone": "+91-9012345038",
        "current_address": "Flat 301, Kukatpally, Hyderabad 500072",
        "permanent_address": "H.No 8-34, Eluru 534001",
        "password": "123456",
    },
    {
        "employee_code": "IPG-039",
        "first_name": "Santosh Kumar", "last_name": "Singh",
        "work_email": "santosh.singh@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345039", "gender": "Male",
        "date_of_birth": datetime.date(1994, 6, 7),
        "date_of_joining": datetime.date(2020, 9, 14),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "PCR",
        "sub_department": "Purchase Operations", "designation_name": "Executive",
        "team": "Procurement", "work_mode": "On-site", "numeric_band": 6, "annual_ctc": 520000,
        "reporting_manager_code": "IPG-017",
        "pan": "MMMSS9012M", "bank_name": "Canara Bank", "bank_account_no": "12312345039", "bank_ifsc": "CNRB0004567",
        "qualification": "B.Com", "institute": "Andhra University", "specialization": "Commerce",
        "year_of_passing": 2016, "previous_employer": "Grasim Industries", "experience_years": 6,
        "domain": "Procurement", "skills": "Purchase Orders, Vendor Communication, SAP MM",
        "certifications": "",
        "emergency_contact_name": "Rani Singh", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-8912345139",
        "blood_group": "A-", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "santosh.singh@gmail.com", "personal_phone": "+91-9012345039",
        "current_address": "H.No 3-45, Gajuwaka, Visakhapatnam 530026",
        "permanent_address": "H.No 3-45, Gajuwaka, Visakhapatnam 530026",
        "password": "123456",
    },
    {
        "employee_code": "IPG-040",
        "first_name": "Ravi Teja", "last_name": "Sharma",
        "work_email": "raviteja.sharma@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345040", "gender": "Male",
        "date_of_birth": datetime.date(1993, 1, 29),
        "date_of_joining": datetime.date(2019, 5, 20),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "MFG",
        "sub_department": "Assembly", "designation_name": "Operator",
        "team": "Production", "work_mode": "On-site", "numeric_band": 7, "annual_ctc": 330000,
        "reporting_manager_code": "IPG-023",
        "pan": "NNNRS0123N", "bank_name": "SBI", "bank_account_no": "30012345040", "bank_ifsc": "SBIN0013456",
        "qualification": "ITI", "institute": "Govt ITI Vizag", "specialization": "Mechanic Motor Vehicle",
        "year_of_passing": 2013, "previous_employer": "Bharat Dynamics Ltd", "experience_years": 9,
        "domain": "Manufacturing", "skills": "Assembly, Tool Handling, Work Instructions",
        "certifications": "",
        "emergency_contact_name": "Kamala Sharma", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-8912345140",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "raviteja.s@gmail.com", "personal_phone": "+91-9012345040",
        "current_address": "H.No 6-12, Bhavani Nagar, Visakhapatnam 530024",
        "permanent_address": "H.No 6-12, Bhavani Nagar, Visakhapatnam 530024",
        "password": "123456",
    },
    {
        "employee_code": "IPG-041",
        "first_name": "Naga Sai", "last_name": "Rao",
        "work_email": "nagasai.rao@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345041", "gender": "Male",
        "date_of_birth": datetime.date(1996, 5, 18),
        "date_of_joining": datetime.date(2022, 3, 7),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "WHS",
        "sub_department": "Inventory Control", "designation_name": "Executive",
        "team": "Operations", "work_mode": "On-site", "numeric_band": 6, "annual_ctc": 390000,
        "reporting_manager_code": "IPG-020",
        "pan": "OOONR1234O", "bank_name": "HDFC Bank", "bank_account_no": "50012345041", "bank_ifsc": "HDFC0011234",
        "qualification": "B.Sc", "institute": "Andhra University", "specialization": "Statistics",
        "year_of_passing": 2018, "previous_employer": None, "experience_years": 2,
        "domain": "Inventory", "skills": "Inventory Counts, WMS, Barcode, Excel",
        "certifications": "",
        "emergency_contact_name": "Sai Rao", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345141",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "nagasai.rao@gmail.com", "personal_phone": "+91-9012345041",
        "current_address": "H.No 7-56, Kommadi, Vizag 530048",
        "permanent_address": "H.No 7-56, Kommadi, Vizag 530048",
        "password": "123456",
    },
    {
        "employee_code": "IPG-042",
        "first_name": "Anitha", "last_name": "Krishnan",
        "work_email": "anitha.krishnan@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345042", "gender": "Female",
        "date_of_birth": datetime.date(1995, 12, 3),
        "date_of_joining": datetime.date(2021, 9, 13),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "IT",
        "sub_department": "IT Support", "designation_name": "Executive",
        "team": "IT", "work_mode": "On-site", "numeric_band": 6, "annual_ctc": 520000,
        "reporting_manager_code": "IPG-002",
        "pan": "PPPAK2345P", "bank_name": "ICICI Bank", "bank_account_no": "02612345042", "bank_ifsc": "ICIC0007890",
        "qualification": "B.Tech", "institute": "JNTU Hyderabad", "specialization": "IT",
        "year_of_passing": 2017, "previous_employer": "HCL Infosystems", "experience_years": 5,
        "domain": "IT Support", "skills": "Helpdesk, Windows, Active Directory, Troubleshooting",
        "certifications": "CompTIA A+",
        "emergency_contact_name": "Krishnan A", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345142",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "anitha.k@gmail.com", "personal_phone": "+91-9012345042",
        "current_address": "Flat 404, Kondapur, Hyderabad 500084",
        "permanent_address": "TC-12-34, Trivandrum 695001",
        "password": "123456",
    },
    {
        "employee_code": "IPG-043",
        "first_name": "Bhavani", "last_name": "Chandra",
        "work_email": "bhavani.chandra@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345043", "gender": "Female",
        "date_of_birth": datetime.date(1998, 8, 7),
        "date_of_joining": datetime.date(2022, 7, 4),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-HYD", "department_code": "CRM",
        "sub_department": "Customer Support", "designation_name": "Executive",
        "team": "CRM", "work_mode": "On-site", "numeric_band": 6, "annual_ctc": 380000,
        "reporting_manager_code": "IPG-031",
        "pan": "QQQBC3456Q", "bank_name": "Axis Bank", "bank_account_no": "91512345043", "bank_ifsc": "UTIB0007890",
        "qualification": "B.A.", "institute": "Osmania University", "specialization": "English Literature",
        "year_of_passing": 2020, "previous_employer": None, "experience_years": 2,
        "domain": "Customer Support", "skills": "Communication, Ticket Handling, MS Office",
        "certifications": "",
        "emergency_contact_name": "Ramesh Chandra", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345143",
        "blood_group": "A+", "nationality": "Indian", "marital_status": "Single",
        "personal_email": "bhavani.chandra@gmail.com", "personal_phone": "+91-9012345043",
        "current_address": "Flat 203, Mehdipatnam, Hyderabad 500028",
        "permanent_address": "H.No 9-23, Khammam 507001",
        "password": "123456",
    },
    {
        "employee_code": "IPG-044",
        "first_name": "Siva Prasad", "last_name": "Varma",
        "work_email": "sivaprasad.varma@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345044", "gender": "Male",
        "date_of_birth": datetime.date(1992, 3, 25),
        "date_of_joining": datetime.date(2019, 12, 2),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "FIN",
        "sub_department": "Accounting", "designation_name": "Executive",
        "team": "Finance", "work_mode": "On-site", "numeric_band": 6, "annual_ctc": 550000,
        "reporting_manager_code": "IPG-006",
        "pan": "RRRSV4567R", "bank_name": "SBI", "bank_account_no": "30012345044", "bank_ifsc": "SBIN0014567",
        "qualification": "B.Com", "institute": "Andhra University", "specialization": "Accounting",
        "year_of_passing": 2014, "previous_employer": "PWC India", "experience_years": 8,
        "domain": "Accounts", "skills": "Bookkeeping, Tally, Bank Reconciliation, MIS",
        "certifications": "",
        "emergency_contact_name": "Santha Varma", "emergency_contact_relation": "Mother", "emergency_contact_phone": "+91-8912345144",
        "blood_group": "O+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "sivaprasad.v@gmail.com", "personal_phone": "+91-9012345044",
        "current_address": "H.No 5-89, Srinagar Colony, Vizag 530044",
        "permanent_address": "H.No 5-89, Srinagar Colony, Vizag 530044",
        "password": "123456",
    },
    {
        "employee_code": "IPG-045",
        "first_name": "Geetha", "last_name": "Kumari",
        "work_email": "geetha.kumari@impacgo.com",
        "role_name": "Employee (ESS)",
        "phone": "+91-8912345045", "gender": "Female",
        "date_of_birth": datetime.date(1991, 7, 14),
        "date_of_joining": datetime.date(2018, 2, 12),
        "employment_type": "Full-Time", "status": "Active",
        "branch_code": "IPG-VZG", "department_code": "HR",
        "sub_department": "Payroll & Benefits", "designation_name": "Senior Executive",
        "team": "HR", "work_mode": "On-site", "numeric_band": 5, "annual_ctc": 600000,
        "reporting_manager_code": "IPG-003",
        "pan": "SSSXK5678S", "bank_name": "HDFC Bank", "bank_account_no": "50012345045", "bank_ifsc": "HDFC0012345",
        "qualification": "MBA HR", "institute": "Nagarjuna University", "specialization": "HR",
        "year_of_passing": 2013, "previous_employer": "Aurobindo Pharma", "experience_years": 11,
        "domain": "HR Operations", "skills": "Leave Management, Benefits Administration, HRIS",
        "certifications": "",
        "emergency_contact_name": "Reddy Kumari", "emergency_contact_relation": "Father", "emergency_contact_phone": "+91-8912345145",
        "blood_group": "B+", "nationality": "Indian", "marital_status": "Married",
        "personal_email": "geetha.kumari@gmail.com", "personal_phone": "+91-9012345045",
        "current_address": "H.No 2-78, Hanumanthawaka, Visakhapatnam 530040",
        "permanent_address": "H.No 2-78, Hanumanthawaka, Visakhapatnam 530040",
        "password": "123456",
    },
]

# One representative employee per role (for quick-login summary)
QUICK_LOGIN_BY_ROLE = {
    "Employee (ESS)":        EMPLOYEES[0],   # IPG-001 MD
    "System Administrator":  EMPLOYEES[1],   # IPG-002
    "HR Manager":            EMPLOYEES[2],   # IPG-003
    "HR Executive":          EMPLOYEES[3],   # IPG-004
    "Finance Manager":       EMPLOYEES[5],   # IPG-006
    "Accountant":            EMPLOYEES[6],   # IPG-007
    "Payroll Officer":       EMPLOYEES[8],   # IPG-009
    "Auditor (Read Only)":   EMPLOYEES[9],   # IPG-010
    "Sales Manager":         EMPLOYEES[10],  # IPG-011
    "Sales Executive":       EMPLOYEES[11],  # IPG-012
    "Procurement Manager":   EMPLOYEES[16],  # IPG-017
    "Buyer":                 EMPLOYEES[17],  # IPG-018
    "Warehouse Manager":     EMPLOYEES[19],  # IPG-020
    "Store Keeper":          EMPLOYEES[20],  # IPG-021
    "Production Manager":    EMPLOYEES[22],  # IPG-023
    "Shop Floor Operator":   EMPLOYEES[23],  # IPG-024
    "Quality Inspector":     EMPLOYEES[28],  # IPG-029
    "CRM Executive":         EMPLOYEES[30],  # IPG-031
    "Support Agent":         EMPLOYEES[32],  # IPG-033
    "Approver":              EMPLOYEES[35],  # IPG-036
}
