"""Branded PDF export for every Reports & Analytics screen.

The Flutter client already holds the exact rows/summary/charts it is
showing (after the viewer's filters and drill-down), so it posts that
same data here and gets back a print-ready PDF: company letterhead with
logo, report meta (period, filters, generated by/on), KPI tiles, charts,
and the detail table -- rendered by the shared headless-Chromium pipeline
(template_rendering.render_html_to_pdf) so fonts, colors and layout match
across machines. Every client-supplied string is HTML-escaped; nothing
here ever touches the network (logo is embedded as a data URL, the font
is bundled under report_assets/)."""

import base64
import datetime
import html
import math
import re
from functools import lru_cache
from pathlib import Path

from .template_rendering import TRANSPARENT_PIXEL_DATA_URL, render_html_to_pdf, resolve_company_logo

# Brand palette -- mirrors lib/core/theme/app_colors.dart so a downloaded
# report looks like the app it came from.
_NAVY = "#182234"
_NAVY_SOFT = "#1F2B42"
_BLUE = "#3B6FEF"
_BLUE_50 = "#EEF3FF"
_TEXT = "#1C2434"
_TEXT_SOFT = "#5B6478"
_TEXT_FAINT = "#8A91A3"
_BORDER = "#E6E9F2"
_ZEBRA = "#F7F9FD"
# Chart / KPI accent cycle: blue, green, purple, amber, teal, pink, cyan, red.
_SERIES = ["#3B6FEF", "#17A673", "#7C5CFC", "#E8A325", "#14B8A6", "#EC5A9D", "#0EA5C4", "#E6493F"]

# Status words -> (text, background) pill colors.
_STATUS_COLORS = {
    "approved": ("#0E7A53", "#E3F8EF"), "active": ("#0E7A53", "#E3F8EF"),
    "present": ("#0E7A53", "#E3F8EF"), "completed": ("#0E7A53", "#E3F8EF"),
    "paid": ("#0E7A53", "#E3F8EF"), "hired": ("#0E7A53", "#E3F8EF"),
    "submitted": ("#2453C9", "#E4ECFF"), "in progress": ("#2453C9", "#E4ECFF"),
    "l1 approved": ("#2453C9", "#E4ECFF"), "open": ("#2453C9", "#E4ECFF"),
    "pending": ("#9A6A0C", "#FDF1DC"), "draft": ("#9A6A0C", "#FDF1DC"),
    "sent back": ("#9A6A0C", "#FDF1DC"), "on hold": ("#9A6A0C", "#FDF1DC"),
    "probation": ("#9A6A0C", "#FDF1DC"),
    "rejected": ("#B42F27", "#FBE6E4"), "absent": ("#B42F27", "#FBE6E4"),
    "inactive": ("#B42F27", "#FBE6E4"), "cancelled": ("#B42F27", "#FBE6E4"),
    "terminated": ("#B42F27", "#FBE6E4"), "exited": ("#B42F27", "#FBE6E4"),
}

_NUMERIC_RE = re.compile(r"^[-+]?(₹|\$|rs\.?\s*)?[\d,]+(\.\d+)?\s*(%|h|hrs?|hours?|d|days?|day\(s\))?$", re.I)

_FONT_PATH = Path(__file__).parent / "report_assets" / "Inter.ttf"


@lru_cache(maxsize=1)
def _font_face_css() -> str:
    try:
        data = base64.b64encode(_FONT_PATH.read_bytes()).decode("ascii")
    except OSError:
        return ""
    return (
        "@font-face{font-family:'Inter';font-weight:100 900;font-style:normal;"
        f"src:url(data:font/ttf;base64,{data}) format('truetype');}}"
    )


def _e(value) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def _is_numeric(cell: str) -> bool:
    c = cell.strip()
    return bool(c) and c not in ("—", "-") and bool(_NUMERIC_RE.match(c))


def _numeric_columns(columns: list[str], rows: list[list[str]]) -> set[int]:
    """A column is right-aligned when (almost) every filled cell is a
    number, amount, percentage or duration."""
    out: set[int] = set()
    sample = rows[:400]
    for i in range(len(columns)):
        cells = [r[i].strip() for r in sample if i < len(r) and r[i].strip() not in ("", "—", "-")]
        if cells and sum(_is_numeric(c) for c in cells) >= 0.9 * len(cells):
            out.add(i)
    return out


def _status_columns(columns: list[str]) -> set[int]:
    return {i for i, c in enumerate(columns) if "status" in c.lower()}


def _pill(text: str) -> str:
    fg, bg = _STATUS_COLORS.get(text.strip().lower().replace("_", " "), (_TEXT_SOFT, "#EEF0F5"))
    return f'<span class="pill" style="color:{fg};background:{bg}">{_e(text)}</span>'


def _point_color(label: str, i: int) -> str:
    """A chart slice/segment named after a status keeps that status's
    color (Approved green, Pending amber, Rejected red ...); anything else
    takes the next color in the brand cycle."""
    status = _STATUS_COLORS.get(label.strip().lower().replace("_", " "))
    return status[0] if status else _SERIES[i % len(_SERIES)]


def _fmt_number(v: float) -> str:
    if abs(v - round(v)) < 1e-9:
        return f"{int(round(v)):,}"
    return f"{v:,.1f}"


def _company_info(company) -> dict:
    logo = resolve_company_logo(company) if company is not None else TRANSPARENT_PIXEL_DATA_URL
    name = getattr(company, "name", None) or "Company"
    address = ", ".join(
        p for p in (
            getattr(company, "address_line1", None), getattr(company, "address_line2", None),
            getattr(company, "city", None), getattr(company, "state", None),
            getattr(company, "pincode", None),
        ) if p
    )
    legal = getattr(company, "legal_name", None)
    return {
        "name": name,
        "logo": None if logo == TRANSPARENT_PIXEL_DATA_URL else logo,
        "legal": legal if legal and legal.strip() != name.strip() else None,
        "address": address or None,
        "gstin": getattr(company, "gstin", None),
    }


def _letterhead(info: dict, title: str, period: str | None, generated_at: str, generated_by: str | None) -> str:
    if info["logo"]:
        mark = f'<img class="logo" src="{_e(info["logo"])}" alt="">'
    else:
        initials = "".join(w[0] for w in info["name"].split()[:2]).upper() or "C"
        mark = f'<div class="monogram">{_e(initials)}</div>'
    sub = []
    if info["legal"]:
        sub.append(_e(info["legal"]))
    if info["address"]:
        sub.append(_e(info["address"]))
    if info["gstin"]:
        sub.append(f"GSTIN: {_e(info['gstin'])}")
    meta = [("Report", title)]
    if period:
        meta.append(("Period", period))
    meta.append(("Generated on", generated_at))
    if generated_by:
        meta.append(("Generated by", generated_by))
    meta_rows = "".join(f"<tr><th>{_e(k)}</th><td>{_e(v)}</td></tr>" for k, v in meta)
    return (
        '<header class="letterhead">'
        f'<div class="lh-brand">{mark}<div><div class="company">{_e(info["name"])}</div>'
        f'<div class="company-sub">{"<br>".join(sub)}</div></div></div>'
        f'<table class="lh-meta">{meta_rows}</table></header>'
        '<div class="rule"><span></span></div>'
    )


def _watermark(info: dict) -> str:
    """Fixed-position, so headless Chromium repeats it on every printed
    page; drawn above the content at a very low opacity (like a real
    watermark) so table/card backgrounds never hide it."""
    if info["logo"]:
        return f'<div class="watermark"><img src="{_e(info["logo"])}" alt=""></div>'
    size = max(26, min(68, int(1000 / max(len(info["name"]), 1))))
    return f'<div class="watermark text"><span style="font-size:{size}pt">{_e(info["name"])}</span></div>'


def _kpis(summary: list[dict]) -> str:
    if not summary:
        return ""
    tiles = []
    for i, item in enumerate(summary):
        color = _SERIES[i % len(_SERIES)]
        tiles.append(
            f'<div class="kpi" style="border-left-color:{color}">'
            f'<div class="kpi-label">{_e(item.get("label"))}</div>'
            f'<div class="kpi-value">{_e(item.get("value"))}</div></div>'
        )
    return f'<div class="kpis">{"".join(tiles)}</div>'


def _donut_svg(points: list[tuple[str, float]]) -> str:
    total = sum(v for _, v in points) or 1.0
    r, c = 52.0, 2 * math.pi * 52.0
    offset = 0.0
    arcs = []
    for i, (_, v) in enumerate(points):
        length = c * (v / total)
        arcs.append(
            f'<circle r="{r}" cx="70" cy="70" fill="none" stroke="{_point_color(points[i][0], i)}" '
            f'stroke-width="22" stroke-dasharray="{length:.2f} {c - length:.2f}" '
            f'stroke-dashoffset="{-offset:.2f}" transform="rotate(-90 70 70)"/>'
        )
        offset += length
    legend = "".join(
        f'<div class="legend-row"><span class="dot" style="background:{_point_color(label, i)}"></span>'
        f'<span class="legend-label">{_e(label)}</span>'
        f'<span class="legend-value">{_fmt_number(v)} <em>({v / total * 100:.0f}%)</em></span></div>'
        for i, (label, v) in enumerate(points)
    )
    return (
        '<div class="donut"><svg width="140" height="140" viewBox="0 0 140 140">'
        f'<circle r="{r}" cx="70" cy="70" fill="none" stroke="#EEF0F5" stroke-width="22"/>{"".join(arcs)}'
        f'<text x="70" y="68" text-anchor="middle" class="donut-total">{_fmt_number(total)}</text>'
        '<text x="70" y="84" text-anchor="middle" class="donut-caption">TOTAL</text></svg>'
        f'<div class="legend">{legend}</div></div>'
    )


def _hbars(points: list[tuple[str, float]], color: str) -> str:
    peak = max((v for _, v in points), default=0) or 1.0
    rows = "".join(
        f'<div class="bar-row"><div class="bar-label">{_e(label)}</div>'
        f'<div class="bar-track"><div class="bar-fill" style="width:{max(v / peak * 100, 0.8):.1f}%;background:{color}"></div></div>'
        f'<div class="bar-value">{_fmt_number(v)}</div></div>'
        for label, v in points
    )
    return f'<div class="bars">{rows}</div>'


_MONTH_YEAR_RE = re.compile(r"^([A-Za-z]{3})[a-z]*\s+(\d{4})$")


_DAY_MONTH_RE = re.compile(r"^(\d{1,2})\s+([A-Za-z]{3})[a-z]*$")


def _short_axis_labels(labels: list[str]) -> list[str]:
    days = [_DAY_MONTH_RE.match(lbl.strip()) for lbl in labels]
    if labels and all(days) and len({m.group(2) for m in days}) == 1:
        return [m.group(1) for m in days]
    matches = [_MONTH_YEAR_RE.match(lbl.strip()) for lbl in labels]
    if not labels or not all(matches):
        return labels
    years = {m.group(2) for m in matches}
    if len(years) == 1:
        return [m.group(1) for m in matches]
    return [f"{m.group(1)} '{m.group(2)[2:]}" for m in matches]


def _columns_chart(points: list[tuple[str, float]], color: str) -> str:
    peak = max((v for _, v in points), default=0) or 1.0
    points = list(zip(_short_axis_labels([lbl for lbl, _ in points]), [v for _, v in points]))
    cols = "".join(
        f'<div class="col"><div class="col-value">{_fmt_number(v)}</div>'
        f'<div class="col-bar" style="height:{max(v / peak * 68, 1.5):.1f}%;background:{color}"></div>'
        f'<div class="col-label">{_e(label)}</div></div>'
        for label, v in points
    )
    return f'<div class="columns">{cols}</div>'


def _stacked(series: list[dict]) -> str:
    labels: list[str] = []
    for s in series:
        for p in s.get("points", []):
            if p["label"] not in labels:
                labels.append(p["label"])
    values = {
        (s["name"], p["label"]): float(p["value"]) for s in series for p in s.get("points", [])
    }
    totals = {lbl: sum(values.get((s["name"], lbl), 0.0) for s in series) for lbl in labels}
    peak = max(totals.values(), default=0) or 1.0
    rows = []
    for lbl in labels[:15]:
        segs = "".join(
            f'<div style="width:{values.get((s["name"], lbl), 0.0) / peak * 100:.2f}%;background:{_point_color(s["name"], i)}"></div>'
            for i, s in enumerate(series)
        )
        rows.append(
            f'<div class="bar-row"><div class="bar-label">{_e(lbl)}</div>'
            f'<div class="bar-track stacked">{segs}</div><div class="bar-value">{_fmt_number(totals[lbl])}</div></div>'
        )
    legend = "".join(
        f'<span class="legend-inline"><span class="dot" style="background:{_point_color(s["name"], i)}"></span>{_e(s["name"])}</span>'
        for i, s in enumerate(series)
    )
    return f'<div class="bars">{"".join(rows)}</div><div class="legend-inline-wrap">{legend}</div>'


def _chart(chart: dict) -> str:
    series = [s for s in chart.get("series", []) if s.get("points")]
    if not series:
        return ""
    kind = chart.get("chart_type", "bar")
    first = [(p["label"], float(p["value"])) for p in series[0]["points"]]
    if kind == "stacked_bar" or len(series) > 1:
        body = _stacked(series)
    elif kind == "donut":
        pts = sorted(first, key=lambda x: x[1], reverse=True)
        if len(pts) > 8:
            pts = pts[:7] + [("Others", sum(v for _, v in pts[7:]))]
        pts = [p for p in pts if p[1] > 0]
        if not pts:
            return ""
        body = _donut_svg(pts)
    elif kind == "line":
        body = _columns_chart(first[-14:], _BLUE)
    else:
        body = _hbars(first[:15], _BLUE)
    return f'<div class="chart"><div class="chart-title">{_e(chart.get("title"))}</div>{body}</div>'


def _table(columns: list[str], rows: list[list[str]]) -> str:
    if not columns:
        return ""
    numeric = _numeric_columns(columns, rows)
    status = _status_columns(columns)
    dates = {i for i, c in enumerate(columns) if re.search(r"\b(date|day|month|period)\b", c.lower())}
    head = '<th class="idx">#</th>' + "".join(
        f'<th class="{"num" if i in numeric else ""}">{_e(c)}</th>' for i, c in enumerate(columns)
    )
    if not rows:
        body = f'<tr><td class="empty" colspan="{len(columns) + 1}">No records for the selected filters.</td></tr>'
    else:
        out = []
        for n, r in enumerate(rows, start=1):
            cells = [f'<td class="idx">{n}</td>']
            for i in range(len(columns)):
                v = r[i] if i < len(r) else ""
                if i in status and v.strip() and v.strip() != "—":
                    cells.append(f"<td>{_pill(v)}</td>")
                elif i in numeric:
                    cells.append(f'<td class="num">{_e(v)}</td>')
                elif i == 0:
                    cells.append(f'<td class="first">{_e(v)}</td>')
                elif i in dates:
                    cells.append(f'<td class="nowrap">{_e(v)}</td>')
                else:
                    cells.append(f"<td>{_e(v)}</td>")
            out.append(f"<tr>{''.join(cells)}</tr>")
        body = "".join(out)
    return f'<table class="data"><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>'


def _css(landscape: bool, kpi_count: int) -> str:
    max_cols = 6 if landscape else 4
    kpi_cols = max(1, min(kpi_count, max_cols))
    return _font_face_css() + f"""
@page {{ size: A4 {'landscape' if landscape else 'portrait'}; margin: 13mm 12mm 17mm 12mm; }}
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; background: #fff; }}
body {{ font-family: 'Inter', 'Segoe UI', Arial, sans-serif; color: {_TEXT}; font-size: 9pt; line-height: 1.45;
  -webkit-print-color-adjust: exact; print-color-adjust: exact; }}

/* Letterhead: plain white, logo + company left, document facts right. */
.letterhead {{ display: flex; justify-content: space-between; align-items: flex-start; gap: 24px; padding: 2px 2px 12px; }}
.lh-brand {{ display: flex; align-items: center; gap: 14px; }}
.logo {{ max-height: 54px; max-width: 170px; object-fit: contain; }}
.monogram {{ width: 50px; height: 50px; border-radius: 10px; background: {_NAVY}; color: #fff; font-weight: 800;
  font-size: 17pt; display: flex; align-items: center; justify-content: center; }}
.company {{ font-size: 15pt; font-weight: 800; color: {_NAVY}; letter-spacing: -.2px; }}
.company-sub {{ font-size: 7.6pt; color: {_TEXT_SOFT}; margin-top: 3px; line-height: 1.55; max-width: {'170mm' if landscape else '105mm'}; }}
.lh-meta {{ border-collapse: collapse; font-size: 7.8pt; }}
.lh-meta th {{ text-align: right; color: {_TEXT_FAINT}; font-weight: 500; padding: 1.5px 10px 1.5px 0; white-space: nowrap; }}
.lh-meta td {{ text-align: left; color: {_TEXT}; font-weight: 600; padding: 1.5px 0; white-space: nowrap; }}
.rule {{ height: 2px; background: {_NAVY}; position: relative; margin-bottom: 18px; }}
.rule span {{ position: absolute; left: 0; top: 0; height: 2px; width: 90px; background: {_BLUE}; }}

/* Watermark on every page (fixed => repeated by Chromium's print). */
.watermark {{ position: fixed; inset: 0; display: flex; align-items: center; justify-content: center;
  z-index: 1000; pointer-events: none; opacity: .045; }}
.watermark img {{ width: {'42%' if landscape else '62%'}; max-height: 55%; object-fit: contain; filter: grayscale(100%); }}
.watermark.text {{ opacity: .04; }}
.watermark.text span {{ transform: rotate(-30deg); font-weight: 800;
  color: {_NAVY}; white-space: nowrap; letter-spacing: 2px; text-transform: uppercase; }}

.title-row {{ display: flex; justify-content: space-between; align-items: flex-end; gap: 16px; margin: 0 2px 10px; }}
h1 {{ font-size: 19pt; margin: 0; font-weight: 800; color: {_NAVY}; letter-spacing: -.3px; line-height: 1.15; }}
.subtitle {{ color: {_TEXT_SOFT}; font-size: 8.8pt; margin-top: 4px; }}
.count-badge {{ font-size: 8pt; color: {_TEXT_SOFT}; white-space: nowrap; padding-bottom: 3px; }}
.count-badge b {{ color: {_NAVY}; font-size: 11pt; font-weight: 800; margin-right: 3px; }}
.filters {{ display: flex; flex-wrap: wrap; gap: 6px; margin: 0 2px 16px; }}
.chip {{ border: 1px solid {_BORDER}; border-radius: 4px; padding: 3px 9px; font-size: 7.6pt; color: {_TEXT_SOFT}; }}
.chip b {{ color: {_TEXT}; font-weight: 600; }}

.section {{ display: flex; align-items: center; gap: 10px; margin: 4px 2px 9px; break-after: avoid; page-break-after: avoid; }}
.section h2 {{ margin: 0; font-size: 10.5pt; font-weight: 700; color: {_NAVY}; white-space: nowrap; }}
.section .num {{ color: {_BLUE}; font-weight: 800; margin-right: 6px; }}
.section .line {{ flex: 1; height: 1px; background: {_BORDER}; }}
.block {{ margin-bottom: 20px; }}
.block.keep {{ break-inside: avoid; }}

/* Detailed records. */
table.data {{ width: 100%; border-collapse: collapse; font-size: {7.5 if landscape else 8}pt; }}
table.data thead {{ display: table-header-group; }}
table.data th {{ background: #F2F5FA; color: {_NAVY}; text-align: left; font-weight: 700; font-size: 7.1pt;
  text-transform: uppercase; letter-spacing: .5px; padding: 7px 8px; border-top: 1px solid {_BORDER};
  border-bottom: 2px solid {_NAVY}; white-space: nowrap; }}
table.data td {{ padding: 6px 8px; border-bottom: 1px solid #EDF0F6; vertical-align: top; overflow-wrap: break-word; }}
table.data tbody tr:nth-child(even) td {{ background: #FAFBFD; }}
table.data tr {{ break-inside: avoid; page-break-inside: avoid; }}
table.data .idx {{ width: 26px; color: {_TEXT_FAINT}; text-align: center; font-variant-numeric: tabular-nums; }}
table.data .num {{ text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }}
table.data td.nowrap {{ white-space: nowrap; }}
table.data td.first {{ font-weight: 600; color: {_NAVY}; }}
table.data td.empty {{ text-align: center; color: {_TEXT_FAINT}; padding: 26px; }}
table.data tbody tr:last-child td {{ border-bottom: 2px solid {_NAVY}; }}
.pill {{ display: inline-block; padding: 1.5px 8px; border-radius: 999px; font-size: 6.9pt; font-weight: 600; white-space: nowrap; }}

/* Summary + insights (after the data). */
.kpis {{ display: grid; grid-template-columns: repeat({kpi_cols}, 1fr); gap: 10px; }}
.kpi {{ border: 1px solid {_BORDER}; border-left: 3px solid {_BLUE}; border-radius: 6px; padding: 9px 12px; break-inside: avoid; }}
.kpi-label {{ font-size: 7pt; color: {_TEXT_SOFT}; text-transform: uppercase; letter-spacing: .6px; font-weight: 600; }}
.kpi-value {{ font-size: 15pt; font-weight: 800; color: {_NAVY}; line-height: 1.2; margin-top: 3px; word-break: break-word; }}
.charts {{ display: grid; grid-template-columns: repeat({3 if landscape else 2}, 1fr); gap: 10px; }}
.chart {{ border: 1px solid {_BORDER}; border-radius: 6px; padding: 11px 12px; break-inside: avoid; }}
.chart-title {{ font-weight: 700; font-size: 8.6pt; margin-bottom: 9px; color: {_NAVY}; }}
.bars {{ display: flex; flex-direction: column; gap: 6px; }}
.bar-row {{ display: grid; grid-template-columns: 36% 1fr 42px; align-items: center; gap: 8px; font-size: 7.6pt; }}
.bar-label {{ color: {_TEXT_SOFT}; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
.bar-track {{ height: 8px; background: #EEF1F6; border-radius: 4px; overflow: hidden; display: flex; }}
.bar-fill {{ height: 100%; border-radius: 4px; }}
.bar-value {{ text-align: right; font-weight: 600; font-variant-numeric: tabular-nums; }}
.legend-inline-wrap {{ margin-top: 8px; display: flex; flex-wrap: wrap; gap: 10px; font-size: 7.3pt; color: {_TEXT_SOFT}; }}
.legend-inline {{ display: inline-flex; align-items: center; gap: 4px; }}
.dot {{ width: 8px; height: 8px; border-radius: 2px; display: inline-block; flex: none; }}
.donut {{ display: flex; align-items: center; gap: 12px; }}
.donut-total {{ font-size: 17px; font-weight: 800; fill: {_NAVY}; font-family: 'Inter', Arial, sans-serif; }}
.donut-caption {{ font-size: 7px; fill: {_TEXT_FAINT}; letter-spacing: 1px; font-family: 'Inter', Arial, sans-serif; }}
.legend {{ flex: 1; display: flex; flex-direction: column; gap: 4px; font-size: 7.6pt; }}
.legend-row {{ display: flex; align-items: center; gap: 6px; }}
.legend-label {{ flex: 1; color: {_TEXT_SOFT}; }}
.legend-value {{ font-weight: 600; font-variant-numeric: tabular-nums; white-space: nowrap; }}
.legend-value em {{ font-style: normal; color: {_TEXT_FAINT}; font-weight: 500; }}
.columns {{ display: flex; align-items: flex-end; gap: 4px; height: 112px; padding-top: 12px; }}
.col {{ flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: flex-end; height: 100%; min-width: 0; }}
.col-bar {{ width: 68%; border-radius: 3px 3px 0 0; }}
.col-value {{ font-size: 6.5pt; font-weight: 600; margin-bottom: 2px; }}
.col-label {{ font-size: 6.3pt; color: {_TEXT_FAINT}; margin-top: 3px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 100%; }}

/* Closing block. */
.end {{ margin-top: 22px; break-inside: avoid; text-align: center; }}
.end-mark {{ display: flex; align-items: center; gap: 12px; color: {_NAVY}; font-size: 8pt; font-weight: 700;
  letter-spacing: 2.5px; text-transform: uppercase; }}
.end-mark::before, .end-mark::after {{ content: ""; flex: 1; height: 1px; background: {_BORDER}; }}
.end-note {{ margin-top: 7px; font-size: 7.4pt; color: {_TEXT_FAINT}; line-height: 1.6; }}
"""


def render_report_pdf(payload: dict, company, generated_by: str | None) -> bytes:
    columns: list[str] = payload.get("columns") or []
    rows: list[list[str]] = payload.get("rows") or []
    summary = payload.get("summary") or []
    landscape = len(columns) > 7
    info = _company_info(company)
    title = payload.get("title") or "Report"
    generated_at = payload.get("generated_at") or datetime.datetime.now().strftime("%d %b %Y, %I:%M %p")
    period = payload.get("period_label")
    subtitle = payload.get("subtitle")

    filters = "".join(
        f'<span class="chip">{_e(f.get("label"))}: <b>{_e(f.get("value"))}</b></span>'
        for f in payload.get("filters") or [] if f.get("value")
    )
    charts = "".join(_chart(c) for c in payload.get("charts") or [])
    record_word = "record" if len(rows) == 1 else "records"

    # Order: the data first, then its summary and insights, then the close.
    sections = []
    n = 0

    def section(name: str) -> str:
        nonlocal n
        n += 1
        return f'<div class="section"><h2><span class="num">{n:02d}</span>{_e(name)}</h2><span class="line"></span></div>'

    sections.append(f'{section("Detailed Records")}<div class="block">{_table(columns, rows)}</div>')
    if summary:
        sections.append(f'<div class="block keep">{section("Summary")}{_kpis(summary)}</div>')
    if charts:
        sections.append(f'{section("Insights")}<div class="block charts">{charts}</div>')

    by = f" by {_e(generated_by)}" if generated_by else ""
    body = f"""
{_watermark(info)}
{_letterhead(info, title, period, generated_at, generated_by)}
<div class="title-row"><div><h1>{_e(title)}</h1>
  {f'<div class="subtitle">{_e(subtitle)}</div>' if subtitle else ''}</div>
  <div class="count-badge"><b>{len(rows):,}</b>{record_word}</div></div>
{f'<div class="filters">{filters}</div>' if filters else ''}
{''.join(sections)}
<div class="end"><div class="end-mark">End of Report</div>
  <div class="end-note">{len(rows):,} {record_word} · Generated on {_e(generated_at)}{by}<br>
  This is a system-generated report from {_e(info["name"])} and does not require a signature.
  Confidential — for internal use only.</div></div>
"""
    doc = (
        '<!DOCTYPE html><html><head><meta charset="utf-8">'
        f"<title>{_e(title)}</title><style>{_css(landscape, len(summary))}</style></head>"
        f"<body>{body}</body></html>"
    )
    footer = (
        '<div style="width:100%;font-size:7px;color:#8A91A3;padding:0 12mm;display:flex;'
        "justify-content:space-between;align-items:center;font-family:Arial,sans-serif;\">"
        f"<span style=\"flex:1\">{_e(info['name'])} · {_e(title)}</span>"
        '<span style="flex:1;text-align:center;letter-spacing:1px">CONFIDENTIAL</span>'
        '<span style="flex:1;text-align:right">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span></div>'
    )
    return render_html_to_pdf(
        doc,
        {"display_header_footer": True, "header_template": "<div></div>", "footer_template": footer},
    )
